//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excalibur.Dispatch.AuditLogging.SqlServer {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excalibur.Dispatch.AuditLogging.SqlServer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection string is required..
        /// </summary>
        internal static string SqlServerAuditStore_ConnectionStringRequired {
            get {
                return ResourceManager.GetString("SqlServerAuditStore_ConnectionStringRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleted {Count} audit events older than {CutoffDate}.
        /// </summary>
        internal static string SqlServerAuditStore_DeletedExpiredEvents {
            get {
                return ResourceManager.GetString("SqlServerAuditStore_DeletedExpiredEvents", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity violation detected for event {EventId}: chain link broken.
        /// </summary>
        internal static string SqlServerAuditStore_IntegrityChainBroken {
            get {
                return ResourceManager.GetString("SqlServerAuditStore_IntegrityChainBroken", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity violation detected for event {EventId}: hash mismatch.
        /// </summary>
        internal static string SqlServerAuditStore_IntegrityHashMismatch {
            get {
                return ResourceManager.GetString("SqlServerAuditStore_IntegrityHashMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Integrity verification passed for {EventCount} events from {StartDate} to {EndDate}.
        /// </summary>
        internal static string SqlServerAuditStore_IntegrityVerificationPassed {
            get {
                return ResourceManager.GetString("SqlServerAuditStore_IntegrityVerificationPassed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stored audit event {EventId} with sequence {SequenceNumber}.
        /// </summary>
        internal static string SqlServerAuditStore_StoredAuditEvent {
            get {
                return ResourceManager.GetString("SqlServerAuditStore_StoredAuditEvent", resourceCulture);
            }
        }
    }
}
