#if (UseAzure)
using Excalibur.Dispatch.Configuration;

using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
        services.AddDispatch(dispatch =>
        {
            dispatch.AddHandlersFromAssembly(typeof(Program).Assembly);
#if (UseKafka)
            dispatch.UseKafka(kafka =>
            {
                kafka.BootstrapServers("localhost:9092");
            });
#elif (UseRabbitMQ)
            dispatch.UseRabbitMQ(rmq =>
            {
                rmq.ConnectionString("amqp://guest:guest@localhost:5672/");
            });
#elif (UseAzureServiceBus)
            dispatch.UseAzureServiceBus(asb =>
            {
                asb.ConnectionString(Environment.GetEnvironmentVariable("AzureServiceBus__ConnectionString")
                    ?? throw new InvalidOperationException("AzureServiceBus__ConnectionString is required."));
            });
#elif (UseAwsSqs)
            dispatch.UseAwsSqs(sqs =>
            {
                sqs.UseRegion(Environment.GetEnvironmentVariable("AWS_REGION") ?? "us-east-1");
            });
#elif (UseGooglePubSub)
            dispatch.UseGooglePubSub(pubsub =>
            {
                pubsub.ProjectId(Environment.GetEnvironmentVariable("GOOGLE_CLOUD_PROJECT") ?? "my-project");
            });
#endif
        });

        services.AddAzureFunctionsServerless();
    })
    .Build();

await host.RunAsync().ConfigureAwait(false);
#elif (UseAws)
// AWS Lambda entry point is the Function class.
// See Function.cs for the Lambda handler.
// DI is configured in Startup.cs.
#else
// Google Cloud Functions entry point is auto-generated by the hosting framework.
// See Function.cs for the HTTP function handler.
// DI is configured in Startup.cs.
#endif
