using System.Globalization;

using Excalibur.Compliance;
using Excalibur.Compliance.Audit;
using Excalibur.Compliance.Encryption;

using Microsoft.Extensions.Logging.Abstractions;

namespace Excalibur.Compliance.Tests.Audit;

[Trait("Category", "Unit")]
[Trait("Component", "Compliance")]
public sealed class AuditLogEncryptionServiceShould : IDisposable
{
	private readonly IEncryptionProvider _encryptionProvider = A.Fake<IEncryptionProvider>();
	private readonly AuditLogEncryptionOptions _options = new()
	{
		EncryptFields = ["ActorId", "IpAddress"],
		KeyIdentifier = "test-audit-key"
	};

	private readonly NullLogger<AuditLogEncryptionService> _logger = NullLogger<AuditLogEncryptionService>.Instance;

	// Real provider pair for round-trip tests (Sprint 686 T.2 regression)
	private readonly InMemoryKeyManagementProvider _realKeyManagement;
	private readonly AesGcmEncryptionProvider _realEncryptionProvider;

	public AuditLogEncryptionServiceShould()
	{
		_realKeyManagement = new InMemoryKeyManagementProvider(
			NullLogger<InMemoryKeyManagementProvider>.Instance,
			new InMemoryKeyManagementOptions
			{
				AutoGenerateDefaultKey = true,
				DefaultKeyId = "test-audit-key"
			});
		_realEncryptionProvider = new AesGcmEncryptionProvider(
			_realKeyManagement,
			NullLogger<AesGcmEncryptionProvider>.Instance);
	}

	[Fact]
	public async Task Encrypt_specified_fields()
	{
		A.CallTo(() => _encryptionProvider.EncryptAsync(A<byte[]>._, A<EncryptionContext>._, A<CancellationToken>._))
			.Returns(new EncryptedData
			{
				Ciphertext = [1, 2, 3],
				KeyId = "test-audit-key",
				KeyVersion = 1,
				Algorithm = EncryptionAlgorithm.Aes256Gcm,
				Iv = new byte[12],
				AuthTag = new byte[16]
			});

		var sut = CreateService();
		var entry = CreateAuditEvent();

		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		encrypted.ShouldNotBeNull();
		encrypted.EventId.ShouldBe(entry.EventId);
		encrypted.KeyIdentifier.ShouldBe("test-audit-key");
		encrypted.EncryptedFields.ShouldContainKey("ActorId");
		encrypted.EncryptedFields.ShouldContainKey("IpAddress");
		encrypted.ClearFields.ShouldNotContainKey("ActorId");
	}

	[Fact]
	public async Task Place_unencrypted_fields_in_clear()
	{
		A.CallTo(() => _encryptionProvider.EncryptAsync(A<byte[]>._, A<EncryptionContext>._, A<CancellationToken>._))
			.Returns(new EncryptedData
			{
				Ciphertext = [1, 2, 3],
				KeyId = "test-audit-key",
				KeyVersion = 1,
				Algorithm = EncryptionAlgorithm.Aes256Gcm,
				Iv = new byte[12],
				AuthTag = new byte[16]
			});

		var sut = CreateService();
		var entry = CreateAuditEvent();

		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		encrypted.ClearFields.ShouldContainKey("Action");
		encrypted.ClearFields.ShouldContainKey("ResourceType");
	}

	[Fact]
	public async Task Throw_for_null_entry_on_encrypt()
	{
		var sut = CreateService();

		await Should.ThrowAsync<ArgumentNullException>(
			() => sut.EncryptAsync(null!, CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public async Task Throw_for_null_entry_on_decrypt()
	{
		var sut = CreateService();

		await Should.ThrowAsync<ArgumentNullException>(
			() => sut.DecryptAsync(null!, CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public async Task Decrypt_encrypted_entry()
	{
		var plaintext = System.Text.Encoding.UTF8.GetBytes("test-actor");
		A.CallTo(() => _encryptionProvider.DecryptAsync(A<EncryptedData>._, A<EncryptionContext>._, A<CancellationToken>._))
			.Returns(plaintext);

		var sut = CreateService();

		// Build a valid envelope: [FmtVer:1][KeyVersion:4][IV:12][Ciphertext:N][AuthTag:16]
		// (bd-c1rscn + ADR-336 Amendment 2: byte 0 = format-version discriminator (1), then the
		// little-endian key-version header so decrypt resolves the persisted version).
		const int formatVersionHeaderSize = 1;
		const int keyVersionHeaderSize = sizeof(int);
		var iv = new byte[12];
		var ciphertext = new byte[] { 1, 2, 3 };
		var authTag = new byte[16];
		var envelope = new byte[formatVersionHeaderSize + keyVersionHeaderSize + iv.Length + ciphertext.Length + authTag.Length];
		envelope[0] = 1; // current envelope format version
		System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(
			envelope.AsSpan(formatVersionHeaderSize, keyVersionHeaderSize), 1);
		iv.CopyTo(envelope, formatVersionHeaderSize + keyVersionHeaderSize);
		ciphertext.CopyTo(envelope, formatVersionHeaderSize + keyVersionHeaderSize + iv.Length);
		authTag.CopyTo(envelope, formatVersionHeaderSize + keyVersionHeaderSize + iv.Length + ciphertext.Length);

		var encryptedEntry = new EncryptedAuditEntry
		{
			EventId = "evt-1",
			EncryptedFields = new Dictionary<string, byte[]>
			{
				["ActorId"] = envelope
			},
			ClearFields = new Dictionary<string, string>
			{
				["Action"] = "Login",
				["EventType"] = "System",
				["Outcome"] = "Success",
				["Timestamp"] = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture)
			},
			KeyIdentifier = "test-audit-key",
			Algorithm = EncryptionAlgorithm.Aes256Gcm
		};

		var decrypted = await sut.DecryptAsync(encryptedEntry, CancellationToken.None).ConfigureAwait(false);

		decrypted.ShouldNotBeNull();
		decrypted.EventId.ShouldBe("evt-1");
		decrypted.ActorId.ShouldBe("test-actor");
		decrypted.Action.ShouldBe("Login");
	}

	// =====================================================================
	// Sprint 686 T.2 (7o2is) -- AES-GCM round-trip regression tests
	// These use REAL AesGcmEncryptionProvider + InMemoryKeyManagementProvider
	// to ensure the envelope format [IV:12][CT:N][AuthTag:16] works end-to-end.
	// =====================================================================

	[Fact]
	public async Task RoundTrip_EncryptDecrypt_WithRealProvider()
	{
		// Arrange
		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);
		var decrypted = await sut.DecryptAsync(encrypted, CancellationToken.None).ConfigureAwait(false);

		// Assert
		decrypted.ShouldNotBeNull();
		decrypted.ActorId.ShouldBe(entry.ActorId);
		decrypted.IpAddress.ShouldBe(entry.IpAddress);
		decrypted.Action.ShouldBe(entry.Action);
		decrypted.EventType.ShouldBe(entry.EventType);
		decrypted.Outcome.ShouldBe(entry.Outcome);
		decrypted.ResourceId.ShouldBe(entry.ResourceId);
		decrypted.ResourceType.ShouldBe(entry.ResourceType);
	}

	[Fact]
	public async Task RoundTrip_MultipleFields_WithRealProvider()
	{
		// Arrange -- encrypt 3+ fields
		var options = new AuditLogEncryptionOptions
		{
			EncryptFields = ["ActorId", "IpAddress", "Reason"],
			KeyIdentifier = "test-audit-key"
		};
		var sut = new AuditLogEncryptionService(
			_realEncryptionProvider,
			Microsoft.Extensions.Options.Options.Create(options),
			_logger);

		var entry = CreateAuditEventWithReason("Suspicious login from new device");

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);
		var decrypted = await sut.DecryptAsync(encrypted, CancellationToken.None).ConfigureAwait(false);

		// Assert
		encrypted.EncryptedFields.Count.ShouldBe(3);
		encrypted.EncryptedFields.ShouldContainKey("ActorId");
		encrypted.EncryptedFields.ShouldContainKey("IpAddress");
		encrypted.EncryptedFields.ShouldContainKey("Reason");

		decrypted.ActorId.ShouldBe("user-123");
		decrypted.IpAddress.ShouldBe("192.168.1.1");
		decrypted.Reason.ShouldBe("Suspicious login from new device");
	}

	[Fact]
	public async Task Envelope_HasCorrectSize_WithRealProvider()
	{
		// Arrange
		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		// Assert -- envelope = IV(12) + ciphertext(N) + AuthTag(16)
		// For each encrypted field, verify envelope is at least MinEnvelopeSize (28) bytes
		foreach (var (fieldName, envelope) in encrypted.EncryptedFields)
		{
			envelope.Length.ShouldBeGreaterThanOrEqualTo(33,
				$"Envelope for '{fieldName}' should be at least 33 bytes (1 FmtVer + 4 KeyVersion + 12 IV + 0 CT min + 16 AuthTag)");

			// The original plaintext is the field value encoded as UTF-8
			// envelope.Length should be 1 (FmtVer) + 4 (KeyVersion) + 12 (IV) + plaintextBytes.Length + 16 (AuthTag)
			var expectedLength = 1 + sizeof(int) + 12 + System.Text.Encoding.UTF8.GetByteCount(
				fieldName == "ActorId" ? entry.ActorId : entry.IpAddress!) + 16;
			envelope.Length.ShouldBe(expectedLength,
				$"Envelope for '{fieldName}' size mismatch");
		}
	}

	[Fact]
	public async Task Decrypt_RejectsShortCiphertext()
	{
		// Arrange -- envelope shorter than MinEnvelopeSize (28 bytes = 12 IV + 16 AuthTag)
		var sut = CreateRealService();
		var encryptedEntry = new EncryptedAuditEntry
		{
			EventId = "evt-short",
			EncryptedFields = new Dictionary<string, byte[]>
			{
				["ActorId"] = new byte[10] // Too short
			},
			ClearFields = new Dictionary<string, string>
			{
				["Action"] = "Login",
				["EventType"] = "System",
				["Outcome"] = "Success",
				["Timestamp"] = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture)
			},
			KeyIdentifier = "test-audit-key",
			Algorithm = EncryptionAlgorithm.Aes256Gcm
		};

		// Act & Assert
		await Should.ThrowAsync<EncryptionException>(
			() => sut.DecryptAsync(encryptedEntry, CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public async Task ClearFields_NotEncrypted_WithRealProvider()
	{
		// Arrange
		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		// Assert -- fields not in EncryptFields list should remain in ClearFields
		encrypted.ClearFields.ShouldContainKey("Action");
		encrypted.ClearFields["Action"].ShouldBe("Login");
		encrypted.ClearFields.ShouldContainKey("ResourceType");
		encrypted.ClearFields["ResourceType"].ShouldBe("Session");
		encrypted.ClearFields.ShouldNotContainKey("ActorId");
		encrypted.ClearFields.ShouldNotContainKey("IpAddress");
	}

	// =====================================================================
	// bd-c1rscn (S840, AC-3 + EC-1) — Rotation-safe audit-log encryption.
	// Independent regression locks (author≠impl, TestsDeveloper) using the REAL
	// AesGcmEncryptionProvider + InMemoryKeyManagementProvider so the round-trip-after-rotation
	// proof is end-to-end (mandatory before integration, NFR-2).
	//
	// NON-VACUITY NOTE: a field encrypted under v1 is NOT a valid lock — the pre-fix decrypt
	// hardcoded KeyVersion=1, so a v1 field would still "decrypt" on the broken code. The data
	// loss only bites once the key has rotated and NEW data is encrypted under v2+. These locks
	// therefore encrypt under a rotated (non-v1) key; pre-fix they fail with an AAD/AuthTag
	// mismatch (v1 key applied to v2 ciphertext); post-fix the persisted version is read and they
	// round-trip. RED on pre-fix, GREEN after.
	// =====================================================================

	[Fact]
	public async Task DecryptFieldEncryptedAfterKeyRotation_WithRealProvider()
	{
		// Arrange — rotate the audit key to v2 BEFORE encrypting, so the field is encrypted under
		// the rotated key version (the realistic post-rotation data path).
		_ = await _realKeyManagement.RotateKeyAsync(
				"test-audit-key", EncryptionAlgorithm.Aes256Gcm, purpose: null, expiresAt: null, CancellationToken.None)
			.ConfigureAwait(false);

		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act — encrypt under the rotated (v2) key, then decrypt.
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);
		var decrypted = await sut.DecryptAsync(encrypted, CancellationToken.None).ConfigureAwait(false);

		// Assert — round-trips via the PERSISTED key version. RED on pre-fix (hardcoded v1 → AAD
		// mismatch → EncryptionException); GREEN once decrypt reads the persisted version.
		decrypted.ShouldNotBeNull();
		decrypted.ActorId.ShouldBe(entry.ActorId);
		decrypted.IpAddress.ShouldBe(entry.IpAddress);
	}

	[Fact]
	public async Task DecryptFieldsAcrossMultipleKeyRotations_WithRealProvider()
	{
		// Arrange — entry1 encrypted under v1.
		var sut = CreateRealService();
		var entry1 = CreateAuditEvent();
		var encrypted1 = await sut.EncryptAsync(entry1, CancellationToken.None).ConfigureAwait(false);

		// Rotate v1 → v2, encrypt entry2 under v2.
		_ = await _realKeyManagement.RotateKeyAsync(
				"test-audit-key", EncryptionAlgorithm.Aes256Gcm, purpose: null, expiresAt: null, CancellationToken.None)
			.ConfigureAwait(false);
		var entry2 = CreateAuditEvent();
		var encrypted2 = await sut.EncryptAsync(entry2, CancellationToken.None).ConfigureAwait(false);

		// Rotate v2 → v3 (current); both legacy versions must still decrypt (EC-1 multi-rotation).
		_ = await _realKeyManagement.RotateKeyAsync(
				"test-audit-key", EncryptionAlgorithm.Aes256Gcm, purpose: null, expiresAt: null, CancellationToken.None)
			.ConfigureAwait(false);

		// Act
		var decrypted1 = await sut.DecryptAsync(encrypted1, CancellationToken.None).ConfigureAwait(false);
		var decrypted2 = await sut.DecryptAsync(encrypted2, CancellationToken.None).ConfigureAwait(false);

		// Assert — each field decrypts via its own persisted key version. RED on pre-fix at the v2
		// field (hardcoded v1); GREEN after the fix.
		decrypted1.ActorId.ShouldBe(entry1.ActorId);
		decrypted2.ActorId.ShouldBe(entry2.ActorId);
	}

	[Fact]
	public async Task SurfaceExplicitErrorWhenEncryptionKeyPurged_WithRealProvider()
	{
		// Arrange — encrypt under the active key, then immediately purge the key (crypto-shred).
		var sut = CreateRealService();
		var entry = CreateAuditEvent();
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		_ = await _realKeyManagement.DeleteKeyAsync("test-audit-key", retentionDays: 0, CancellationToken.None)
			.ConfigureAwait(false);

		// Act & Assert — EC-1: decrypt against a purged version surfaces an explicit error,
		// never a silent failure or wrong plaintext.
		await Should.ThrowAsync<EncryptionException>(
			() => sut.DecryptAsync(encrypted, CancellationToken.None)).ConfigureAwait(false);
	}

	// --- bd-c1rscn + ADR-336 Amendment 2 (F-6): envelope format-version discriminator ---
	// Every envelope carries a 1-byte format-version at byte 0, DISTINCT from the key version, so a
	// future envelope-layout change is migratable. Decrypt validates it and rejects an unknown version
	// with a surfaced error rather than misparsing. RED on the pre-F-6 envelope (no format byte/check).

	[Fact]
	public async Task StampEnvelopeFormatVersionDiscriminator_WithRealProvider()
	{
		// Arrange
		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		// Assert — byte 0 of every encrypted field is the format-version discriminator (1).
		encrypted.EncryptedFields.ShouldNotBeEmpty();
		foreach (var (fieldName, envelope) in encrypted.EncryptedFields)
		{
			envelope[0].ShouldBe((byte)1, $"envelope byte 0 for '{fieldName}' must be the format-version discriminator (1)");
		}
	}

	[Fact]
	public async Task RejectUnknownEnvelopeFormatVersionOnDecrypt_WithRealProvider()
	{
		// Arrange — encrypt, then corrupt the format-version discriminator (byte 0) to an unknown value.
		var sut = CreateRealService();
		var entry = CreateAuditEvent();
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		foreach (var (_, envelope) in encrypted.EncryptedFields)
		{
			envelope[0] = 0xFF; // unknown / future format version
		}

		// Act & Assert — decrypt MUST surface an explicit unsupported-format error, not a best-effort
		// misparse. RED on pre-F-6 code (byte 0 was IV data; corrupting it yields an AAD/decrypt error,
		// not a "format version" diagnostic).
		var ex = await Should.ThrowAsync<EncryptionException>(
			() => sut.DecryptAsync(encrypted, CancellationToken.None)).ConfigureAwait(false);
		ex.Message.ShouldContain("format version");
	}

	[Fact]
	public async Task Propagate_encryption_exception()
	{
		A.CallTo(() => _encryptionProvider.EncryptAsync(A<byte[]>._, A<EncryptionContext>._, A<CancellationToken>._))
			.ThrowsAsync(new InvalidOperationException("Key unavailable"));

		var sut = CreateService();

		await Should.ThrowAsync<InvalidOperationException>(
			() => sut.EncryptAsync(CreateAuditEvent(), CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public void Throw_for_null_encryption_provider()
	{
		Should.Throw<ArgumentNullException>(() =>
			new AuditLogEncryptionService(
				null!,
				Microsoft.Extensions.Options.Options.Create(_options),
				_logger));
	}

	[Fact]
	public void Throw_for_null_options()
	{
		Should.Throw<ArgumentNullException>(() =>
			new AuditLogEncryptionService(
				_encryptionProvider,
				null!,
				_logger));
	}

	[Fact]
	public void Throw_for_null_logger()
	{
		Should.Throw<ArgumentNullException>(() =>
			new AuditLogEncryptionService(
				_encryptionProvider,
				Microsoft.Extensions.Options.Options.Create(_options),
				null!));
	}

	public void Dispose()
	{
		_realEncryptionProvider.Dispose();
		_realKeyManagement.Dispose();
	}

	private AuditLogEncryptionService CreateService() =>
		new(
			_encryptionProvider,
			Microsoft.Extensions.Options.Options.Create(_options),
			_logger);

	private AuditLogEncryptionService CreateRealService() =>
		new(
			_realEncryptionProvider,
			Microsoft.Extensions.Options.Options.Create(_options),
			_logger);

	private static AuditEvent CreateAuditEvent() =>
		new()
		{
			EventId = "evt-" + Guid.NewGuid().ToString("N")[..8],
			EventType = AuditEventType.Authentication,
			Action = "Login",
			Outcome = AuditOutcome.Success,
			Timestamp = DateTimeOffset.UtcNow,
			ActorId = "user-123",
			ActorType = "User",
			ResourceId = "resource-1",
			ResourceType = "Session",
			IpAddress = "192.168.1.1"
		};

	private static AuditEvent CreateAuditEventWithReason(string reason) =>
		new()
		{
			EventId = "evt-" + Guid.NewGuid().ToString("N")[..8],
			EventType = AuditEventType.Authentication,
			Action = "Login",
			Outcome = AuditOutcome.Success,
			Timestamp = DateTimeOffset.UtcNow,
			ActorId = "user-123",
			ActorType = "User",
			ResourceId = "resource-1",
			ResourceType = "Session",
			IpAddress = "192.168.1.1",
			Reason = reason
		};
}
