//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excalibur.EventSourcing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excalibur.EventSourcing.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one strategy must be provided..
        /// </summary>
        internal static string CompositeSnapshotStrategy_AtLeastOneStrategyMustBeProvided {
            get {
                return ResourceManager.GetString("CompositeSnapshotStrategy_AtLeastOneStrategyMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown composite mode: {0}.
        /// </summary>
        internal static string CompositeSnapshotStrategy_UnknownCompositeModeFormat {
            get {
                return ResourceManager.GetString("CompositeSnapshotStrategy_UnknownCompositeModeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize encrypted data envelope..
        /// </summary>
        internal static string Encryption_FailedToDeserializeEncryptedDataEnvelope {
            get {
                return ResourceManager.GetString("Encryption_FailedToDeserializeEncryptedDataEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registered provider can decrypt this data. The encryption key may have been removed..
        /// </summary>
        internal static string Encryption_NoProviderCanDecrypt {
            get {
                return ResourceManager.GetString("Encryption_NoProviderCanDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event store is in read-only mode. Writes are not permitted during this encryption migration phase..
        /// </summary>
        internal static string Encryption_ReadOnlyEventStore {
            get {
                return ResourceManager.GetString("Encryption_ReadOnlyEventStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection store is in read-only mode. Writes are not permitted during this encryption migration phase..
        /// </summary>
        internal static string Encryption_ReadOnlyProjectionStore {
            get {
                return ResourceManager.GetString("Encryption_ReadOnlyProjectionStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate ID cannot convert to null string..
        /// </summary>
        internal static string EventSourcedRepository_AggregateIdCannotConvertToNullString {
            get {
                return ResourceManager.GetString("EventSourcedRepository_AggregateIdCannotConvertToNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete operation requires a tombstone event implementation. Override DeleteAsync in a derived repository class for aggregate {0}..
        /// </summary>
        internal static string EventSourcedRepository_DeleteRequiresTombstoneFormat {
            get {
                return ResourceManager.GetString("EventSourcedRepository_DeleteRequiresTombstoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find operation requires a query executor implementation. Override FindAsync in a derived repository class or inject an IQueryExecutor&lt;{0}&gt;..
        /// </summary>
        internal static string EventSourcedRepository_FindRequiresExecutorFormat {
            get {
                return ResourceManager.GetString("EventSourcedRepository_FindRequiresExecutorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query operation requires a query executor implementation. Override QueryAsync in a derived repository class or inject an IQueryExecutor&lt;{0}&gt;..
        /// </summary>
        internal static string EventSourcedRepository_QueryRequiresExecutorFormat {
            get {
                return ResourceManager.GetString("EventSourcedRepository_QueryRequiresExecutorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save aggregate {0}: {1}.
        /// </summary>
        internal static string EventSourcedRepository_SaveFailedFormat {
            get {
                return ResourceManager.GetString("EventSourcedRepository_SaveFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type cannot be null or empty..
        /// </summary>
        internal static string EventVersionManager_EventTypeCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("EventVersionManager_EventTypeCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upgrade path found for {0} from version {1} to {2}..
        /// </summary>
        internal static string EventVersionManager_NoUpgradePathFoundFormat {
            get {
                return ResourceManager.GetString("EventVersionManager_NoUpgradePathFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upgraders registered for event type {0}..
        /// </summary>
        internal static string EventVersionManager_NoUpgradersRegisteredFormat {
            get {
                return ResourceManager.GetString("EventVersionManager_NoUpgradersRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An upgrader for {0} from version {1} to {2} already exists..
        /// </summary>
        internal static string EventVersionManager_UpgraderAlreadyExistsFormat {
            get {
                return ResourceManager.GetString("EventVersionManager_UpgraderAlreadyExistsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum size must be greater than zero..
        /// </summary>
        internal static string SizeBasedSnapshotStrategy_MaxSizeMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("SizeBasedSnapshotStrategy_MaxSizeMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be greater than zero..
        /// </summary>
        internal static string TimeBasedSnapshotStrategy_IntervalMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TimeBasedSnapshotStrategy_IntervalMustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}
