// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using System.Diagnostics.CodeAnalysis;

using Excalibur.Compliance;
using Excalibur.Compliance.Configuration;
using Excalibur.Compliance.Diagnostics;
using Excalibur.Compliance.Encryption;

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Extension methods for configuring encryption services with the pluggable provider registry.
/// </summary>
public static class EncryptionServiceCollectionExtensions
{
	/// <summary>
	/// Adds the encryption provider registry and configures encryption services.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <param name="configure">Action to configure the encryption services using the fluent builder.</param>
	/// <returns>The service collection for chaining.</returns>
	/// <example>
	/// <code>
	/// services.AddEncryption(encryption => encryption
	///     .UseKeyManagement&lt;AesGcmEncryptionProvider&gt;("aes-gcm-primary")
	///     .ConfigureOptions(options => options.DefaultPurpose = "field-encryption"));
	/// </code>
	/// </example>
	public static IServiceCollection AddEncryption(
		this IServiceCollection services,
		Action<EncryptionConfigurationBuilder> configure)
	{
		ArgumentNullException.ThrowIfNull(services);
		ArgumentNullException.ThrowIfNull(configure);

		// Register the registry as a singleton.
		services.TryAddSingleton<IEncryptionProviderRegistry, EncryptionProviderRegistry>();

		// Create and execute the builder.
		var builder = new EncryptionConfigurationBuilder(services);
		configure(builder);

		// Validate that at least one provider was registered.
		builder.Validate();

		// Encryption is a durability-requiring composition: keys that vanish on restart make every value
		// encrypted under them permanently unrecoverable. Install the startup gate so a volatile key
		// provider FAILS CLOSED unless the host opted in explicitly (UseInMemoryKeyManagement sets
		// AllowVolatileKeyProvider = true). The gate resolves the provider that actually won registration.
		services.AddKeyDurabilityGate();

		return services;
	}

	/// <summary>
	/// Adds development-only encryption services with an in-memory provider.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <returns>The service collection for chaining.</returns>
	/// <remarks>
	/// <para>
	/// <strong>WARNING:</strong> This method is for development and testing only.
	/// Do not use in production as keys are stored in memory and not persisted.
	/// </para>
	/// <para>
	/// A warning is logged when the host starts, to alert developers that this configuration
	/// is not suitable for production use.
	/// </para>
	/// </remarks>
	public static IServiceCollection AddDevEncryption(this IServiceCollection services)
	{
		ArgumentNullException.ThrowIfNull(services);

		// Emit the warning from a hosted service. Registering a plain singleton would never warn: the
		// container only constructs a singleton when something resolves it, and nothing resolves this.
		services.TryAddEnumerable(ServiceDescriptor.Singleton<IHostedService, DevEncryptionWarningLogger>());

		return services.AddEncryption(encryption => encryption
			.UseInMemoryKeyManagement("dev-inmemory", options =>
			{
				options.AutoGenerateDefaultKey = true;
			})
			.SetAsPrimary("dev-inmemory"));
	}

	/// <summary>
	/// Adds HKDF (RFC 5869) key derivation services.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <param name="configure">Optional configuration for HKDF key derivation options.</param>
	/// <returns>The service collection for chaining.</returns>
	public static IServiceCollection AddHkdfKeyDerivation(
		this IServiceCollection services,
		Action<HkdfKeyDerivationOptions>? configure = null)
	{
		ArgumentNullException.ThrowIfNull(services);

		var optionsBuilder = services.AddOptions<HkdfKeyDerivationOptions>()
			.ValidateOnStart();
		services.TryAddEnumerable(
			ServiceDescriptor.Singleton<IValidateOptions<HkdfKeyDerivationOptions>, HkdfKeyDerivationOptionsValidator>());
		if (configure is not null)
		{
			_ = optionsBuilder.Configure(configure);
		}

		services.TryAddSingleton<HkdfKeyDeriver>();

		return services;
	}

	/// <summary>
	/// Adds HKDF (RFC 5869) key derivation services using an <see cref="IConfiguration"/> section.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <param name="configuration">The configuration section to bind to <see cref="HkdfKeyDerivationOptions"/>.</param>
	/// <returns>The service collection for chaining.</returns>
	public static IServiceCollection AddHkdfKeyDerivation(
		this IServiceCollection services,
		IConfiguration configuration)
	{
		ArgumentNullException.ThrowIfNull(services);
		ArgumentNullException.ThrowIfNull(configuration);

		_ = services.AddOptions<HkdfKeyDerivationOptions>().Bind(configuration).ValidateOnStart();
		services.TryAddEnumerable(
			ServiceDescriptor.Singleton<IValidateOptions<HkdfKeyDerivationOptions>, HkdfKeyDerivationOptionsValidator>());

		services.TryAddSingleton<HkdfKeyDeriver>();

		return services;
	}
}

/// <summary>
/// Hosted service that warns at startup when development-only encryption is active.
/// </summary>
internal sealed partial class DevEncryptionWarningLogger : IHostedService
{
	private readonly ILogger<DevEncryptionWarningLogger> _logger;

	public DevEncryptionWarningLogger(ILogger<DevEncryptionWarningLogger> logger)
	{
		ArgumentNullException.ThrowIfNull(logger);

		_logger = logger;
	}

	/// <inheritdoc/>
	public Task StartAsync(CancellationToken cancellationToken)
	{
		LogDevEncryptionWarning(_logger);
		return Task.CompletedTask;
	}

	/// <inheritdoc/>
	public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

	[LoggerMessage(ComplianceEventId.DevEncryptionWarning, LogLevel.Warning,
			"DEV ENCRYPTION IS ACTIVE. In-memory key management is being used. Keys are not persisted and will be lost on restart. Do NOT use this configuration in production. Configure a production key management provider using AddEncryption().")]
	private static partial void LogDevEncryptionWarning(ILogger logger);
}
