// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.1 OR AGPL-3.0-or-later OR SSPL-1.0


#pragma warning disable IDE0270 // Null check can be simplified

using Excalibur.Compliance;

namespace Excalibur.Testing.Conformance;

/// <summary>
/// Abstract base class for IKeyManagementProvider and IKeyManagementAdmin conformance testing.
/// </summary>
/// <remarks>
/// <para>
/// Inherit from this class and implement <see cref="CreateProvider"/> to verify that
/// your key management provider implementation conforms to the IKeyManagementProvider
/// and IKeyManagementAdmin contracts.
/// </para>
/// <para>
/// The test kit verifies core key management operations including:
/// <list type="bullet">
/// <item><description>Key creation via RotateKeyAsync (first call creates new key)</description></item>
/// <item><description>Key rotation with version management (creates new version, marks old as DecryptOnly)</description></item>
/// <item><description>Key retrieval by ID and by version</description></item>
/// <item><description>Key listing with status and purpose filtering (via IKeyManagementAdmin)</description></item>
/// <item><description>Key deletion with retention period -- crypto-shredding for GDPR (via IKeyManagementAdmin)</description></item>
/// <item><description>Key suspension for security incidents (via IKeyManagementAdmin)</description></item>
/// <item><description>Active key retrieval with purpose filtering</description></item>
/// </list>
/// </para>
/// <para>
/// <strong>COMPLIANCE-CRITICAL:</strong> IKeyManagementProvider and IKeyManagementAdmin implement
/// key lifecycle management for encryption and GDPR Right to Erasure via crypto-shredding:
/// <list type="bullet">
/// <item><description>Keys follow lifecycle: Active -> DecryptOnly -> PendingDestruction -> Destroyed</description></item>
/// <item><description>RotateKeyAsync creates new version, does NOT throw on existing key</description></item>
/// <item><description>DeleteKeyAsync schedules deletion with retention period (crypto-shredding)</description></item>
/// <item><description>SuspendKeyAsync immediately prevents key usage for security incidents</description></item>
/// <item><description>IDisposable implementations must securely clear key material</description></item>
/// </list>
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // The provider is resolved from a container built by its own registration extension, so the
/// // arms certify the object a consumer actually gets. AddAwsKmsKeyManagement is shown here;
/// // AddAzureKeyVaultKeyManagement and AddVaultKeyManagement follow the same shape.
/// public class AwsKmsKeyManagementProviderConformanceTests : KeyManagementProviderConformanceTestKit
/// {
///     private readonly ServiceProvider _provider;
///
///     public AwsKmsKeyManagementProviderConformanceTests(LocalStackFixture fixture) =&gt;
///         _provider = new ServiceCollection()
///             .AddLogging()
///             .AddAwsKmsKeyManagement(aws =&gt; aws.ServiceUrl(fixture.ServiceUrl))
///             .BuildServiceProvider();
///
///     protected override IKeyManagementProvider CreateProvider() =&gt;
///         _provider.GetRequiredService&lt;IKeyManagementProvider&gt;();
/// }
/// </code>
/// </example>
[System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores",
	Justification = "Test method naming convention")]
public abstract class KeyManagementProviderConformanceTestKit : ConformanceTestKit
{
	/// <summary>
	/// Creates a fresh key management provider instance for testing.
	/// </summary>
	/// <returns>An IKeyManagementProvider implementation to test.</returns>
	/// <remarks>
	/// <para>
	/// For InMemoryKeyManagementProvider, configure with AutoGenerateDefaultKey = false
	/// to ensure test isolation:
	/// </para>
	/// <code>
	/// protected override IKeyManagementProvider CreateProvider() =>
	///     new InMemoryKeyManagementProvider(
	///         NullLogger&lt;InMemoryKeyManagementProvider&gt;.Instance,
	///         new InMemoryKeyManagementOptions { AutoGenerateDefaultKey = false });
	/// </code>
	/// </remarks>
	protected abstract IKeyManagementProvider CreateProvider();

	/// <summary>
	/// Creates a fresh key management admin instance for testing admin operations
	/// (listing, deletion, suspension).
	/// </summary>
	/// <returns>An IKeyManagementAdmin implementation to test.</returns>
	/// <remarks>
	/// <para>
	/// The default implementation casts the result of <see cref="CreateProvider"/> to
	/// <see cref="IKeyManagementAdmin"/>, which works for all built-in providers since
	/// they implement both interfaces. Override this method if your provider uses a
	/// separate admin implementation.
	/// </para>
	/// </remarks>
	protected virtual IKeyManagementAdmin CreateAdmin() => (IKeyManagementAdmin)CreateProvider();

	/// <summary>
	/// Optional cleanup after each test.
	/// </summary>
	/// <returns>A task representing the cleanup operation.</returns>
	protected virtual Task CleanupAsync() => Task.CompletedTask;

	/// <summary>
	/// Generates a unique key ID for test isolation.
	/// </summary>
	/// <returns>A unique key identifier.</returns>
	protected virtual string GenerateKeyId() => $"test-key-{Guid.NewGuid():N}";

	#region GetKey Tests

	/// <summary>
	/// Verifies that GetKeyAsync returns null for non-existent key.
	/// </summary>
	public virtual async Task GetKeyAsync_NonExistent_ShouldReturnNull()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			// Act
			var result = await provider.GetKeyAsync("non-existent-key", CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is not null)
			{
				throw new TestFixtureAssertionException(
					"Expected GetKeyAsync to return null for non-existent key, but got a result.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that GetKeyAsync throws ArgumentException for null or empty keyId.
	/// </summary>
	public virtual async Task GetKeyAsync_NullKeyId_ShouldThrowArgumentException()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			// Act & Assert
			var caughtException = false;
			try
			{
				_ = await provider.GetKeyAsync(null!, CancellationToken.None).ConfigureAwait(false);
			}
			catch (ArgumentException)
			{
				caughtException = true;
			}

			if (!caughtException)
			{
				throw new TestFixtureAssertionException(
					"Expected GetKeyAsync to throw ArgumentException for null keyId.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that GetKeyAsync returns the latest version of a key.
	/// </summary>
	public virtual async Task GetKeyAsync_ExistingKey_ShouldReturnLatestVersion()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			// Create key (version 1)
			var createResult = await provider.RotateKeyAsync(
				keyId,
				EncryptionAlgorithm.Aes256Gcm,
				purpose: "test-purpose",
				expiresAt: null,
				CancellationToken.None).ConfigureAwait(false);

			if (!createResult.Success)
			{
				throw new TestFixtureAssertionException($"Failed to create key: {createResult.ErrorMessage}");
			}

			// Rotate to version 2
			var rotateResult = await provider.RotateKeyAsync(
				keyId,
				EncryptionAlgorithm.Aes256Gcm,
				purpose: "test-purpose",
				expiresAt: null,
				CancellationToken.None).ConfigureAwait(false);

			if (!rotateResult.Success)
			{
				throw new TestFixtureAssertionException($"Failed to rotate key: {rotateResult.ErrorMessage}");
			}

			// Act
			var result = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is null)
			{
				throw new TestFixtureAssertionException("Expected GetKeyAsync to return key metadata.");
			}

			if (result.Version != 2)
			{
				throw new TestFixtureAssertionException(
					$"Expected GetKeyAsync to return version 2, but got version {result.Version}.");
			}

			if (result.Status != KeyStatus.Active)
			{
				throw new TestFixtureAssertionException(
					$"Expected latest version to be Active, but got {result.Status}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region GetKeyVersion Tests

	/// <summary>
	/// Verifies that GetKeyVersionAsync returns null for non-existent version.
	/// </summary>
	public virtual async Task GetKeyVersionAsync_NonExistentVersion_ShouldReturnNull()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			// Create key (version 1)
			_ = await provider.RotateKeyAsync(
				keyId,
				EncryptionAlgorithm.Aes256Gcm,
				purpose: null,
				expiresAt: null,
				CancellationToken.None).ConfigureAwait(false);

			// Act
			var result = await provider.GetKeyVersionAsync(keyId, 999, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is not null)
			{
				throw new TestFixtureAssertionException(
					"Expected GetKeyVersionAsync to return null for non-existent version.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that GetKeyVersionAsync returns the correct version metadata.
	/// </summary>
	public virtual async Task GetKeyVersionAsync_ExistingVersion_ShouldReturnCorrectMetadata()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			// Create key (version 1)
			_ = await provider.RotateKeyAsync(
				keyId,
				EncryptionAlgorithm.Aes256Gcm,
				purpose: "encryption",
				expiresAt: null,
				CancellationToken.None).ConfigureAwait(false);

			// Rotate to version 2
			_ = await provider.RotateKeyAsync(
				keyId,
				EncryptionAlgorithm.Aes256Gcm,
				purpose: "encryption",
				expiresAt: null,
				CancellationToken.None).ConfigureAwait(false);

			// Act - get version 1
			var result = await provider.GetKeyVersionAsync(keyId, 1, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is null)
			{
				throw new TestFixtureAssertionException("Expected GetKeyVersionAsync to return key metadata.");
			}

			if (result.Version != 1)
			{
				throw new TestFixtureAssertionException(
					$"Expected version 1, but got version {result.Version}.");
			}

			if (result.Status != KeyStatus.DecryptOnly)
			{
				throw new TestFixtureAssertionException(
					$"Expected version 1 to be DecryptOnly after rotation, but got {result.Status}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region ListKeys Tests

	/// <summary>
	/// Verifies that ListKeysAsync returns empty list when no keys exist.
	/// </summary>
	public virtual async Task ListKeysAsync_NoKeys_ShouldReturnEmptyList()
	{
		// Arrange
		var admin = CreateAdmin();
		try
		{
			// Act
			var result = await admin.ListKeysAsync(null, null, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is null)
			{
				throw new TestFixtureAssertionException("Expected ListKeysAsync to return a list, not null.");
			}

			if (result.Count != 0)
			{
				throw new TestFixtureAssertionException(
					$"Expected empty list when no keys exist, but got {result.Count} keys.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(admin as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that ListKeysAsync filters by status correctly.
	/// </summary>
	public virtual async Task ListKeysAsync_FilterByStatus_ShouldFilterCorrectly()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId1 = GenerateKeyId();
			var keyId2 = GenerateKeyId();

			// Create two active keys
			_ = await provider.RotateKeyAsync(keyId1, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);
			_ = await provider.RotateKeyAsync(keyId2, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Suspend one key
			_ = await admin.SuspendKeyAsync(keyId1, "test-suspension", CancellationToken.None).ConfigureAwait(false);

			// Act - filter by Active
			var activeKeys = await admin.ListKeysAsync(KeyStatus.Active, null, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (activeKeys.Count != 1)
			{
				throw new TestFixtureAssertionException(
					$"Expected 1 active key, but got {activeKeys.Count}.");
			}

			if (activeKeys[0].KeyId != keyId2)
			{
				throw new TestFixtureAssertionException(
					$"Expected active key to be {keyId2}, but got {activeKeys[0].KeyId}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that ListKeysAsync filters by purpose correctly.
	/// </summary>
	public virtual async Task ListKeysAsync_FilterByPurpose_ShouldFilterCorrectly()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId1 = GenerateKeyId();
			var keyId2 = GenerateKeyId();

			// Create keys with different purposes
			_ = await provider.RotateKeyAsync(keyId1, EncryptionAlgorithm.Aes256Gcm, "encryption", null, CancellationToken.None)
				.ConfigureAwait(false);
			_ = await provider.RotateKeyAsync(keyId2, EncryptionAlgorithm.Aes256Gcm, "signing", null, CancellationToken.None)
				.ConfigureAwait(false);

			// Act - filter by purpose
			var encryptionKeys = await admin.ListKeysAsync(null, "encryption", CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (encryptionKeys.Count != 1)
			{
				throw new TestFixtureAssertionException(
					$"Expected 1 key with purpose 'encryption', but got {encryptionKeys.Count}.");
			}

			if (encryptionKeys[0].KeyId != keyId1)
			{
				throw new TestFixtureAssertionException(
					$"Expected key {keyId1}, but got {encryptionKeys[0].KeyId}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region RotateKey Tests

	/// <summary>
	/// Verifies that RotateKeyAsync creates a new key when one doesn't exist.
	/// </summary>
	public virtual async Task RotateKeyAsync_NewKey_ShouldCreateVersion1()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			// Act
			var result = await provider.RotateKeyAsync(
				keyId,
				EncryptionAlgorithm.Aes256Gcm,
				purpose: "test",
				expiresAt: DateTimeOffset.UtcNow.AddDays(30),
				CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (!result.Success)
			{
				throw new TestFixtureAssertionException($"Expected RotateKeyAsync to succeed: {result.ErrorMessage}");
			}

			if (result.NewKey is null)
			{
				throw new TestFixtureAssertionException("Expected NewKey to be populated.");
			}

			if (result.NewKey.Version != 1)
			{
				throw new TestFixtureAssertionException(
					$"Expected new key to be version 1, but got {result.NewKey.Version}.");
			}

			if (result.NewKey.Status != KeyStatus.Active)
			{
				throw new TestFixtureAssertionException(
					$"Expected new key to be Active, but got {result.NewKey.Status}.");
			}

			if (result.PreviousKey is not null)
			{
				throw new TestFixtureAssertionException(
					"Expected PreviousKey to be null for new key creation.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that RotateKeyAsync increments version and marks old as DecryptOnly.
	/// </summary>
	public virtual async Task RotateKeyAsync_ExistingKey_ShouldCreateNewVersionAndMarkOldDecryptOnly()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			// Create key (version 1)
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Act - rotate to version 2
			var result = await provider.RotateKeyAsync(
				keyId,
				EncryptionAlgorithm.Aes256Gcm,
				purpose: null,
				expiresAt: null,
				CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (!result.Success)
			{
				throw new TestFixtureAssertionException($"Expected rotation to succeed: {result.ErrorMessage}");
			}

			if (result.NewKey is null)
			{
				throw new TestFixtureAssertionException("Expected NewKey to be populated.");
			}

			if (result.NewKey.Version != 2)
			{
				throw new TestFixtureAssertionException(
					$"Expected new key to be version 2, but got {result.NewKey.Version}.");
			}

			if (result.PreviousKey is null)
			{
				throw new TestFixtureAssertionException("Expected PreviousKey to be populated for rotation.");
			}

			if (result.PreviousKey.Version != 1)
			{
				throw new TestFixtureAssertionException(
					$"Expected previous key to be version 1, but got {result.PreviousKey.Version}.");
			}

			// Verify previous version is now DecryptOnly
			var v1Metadata = await provider.GetKeyVersionAsync(keyId, 1, CancellationToken.None).ConfigureAwait(false);
			if (v1Metadata is null)
			{
				throw new TestFixtureAssertionException("Expected version 1 to still exist.");
			}

			if (v1Metadata.Status != KeyStatus.DecryptOnly)
			{
				throw new TestFixtureAssertionException(
					$"Expected version 1 to be DecryptOnly, but got {v1Metadata.Status}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that RotateKeyAsync throws for null keyId.
	/// </summary>
	public virtual async Task RotateKeyAsync_NullKeyId_ShouldThrowArgumentException()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			// Act & Assert
			var caughtException = false;
			try
			{
				_ = await provider.RotateKeyAsync(null!, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
					.ConfigureAwait(false);
			}
			catch (ArgumentException)
			{
				caughtException = true;
			}

			if (!caughtException)
			{
				throw new TestFixtureAssertionException(
					"Expected RotateKeyAsync to throw ArgumentException for null keyId.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region CreateKeyIfAbsent Tests

	/// <summary>
	/// Verifies that provisioning an absent key creates exactly one usable version.
	/// </summary>
	/// <remarks>
	/// LIVENESS. Without this, every safety arm below is satisfied by a provider that creates nothing at all.
	/// </remarks>
	public virtual async Task CreateKeyIfAbsentAsync_WhenAbsent_ShouldCreateOneActiveVersion()
	{
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			var created = await provider
				.CreateKeyIfAbsentAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, CancellationToken.None)
				.ConfigureAwait(false);

			if (created.Status != KeyStatus.Active)
			{
				throw new TestFixtureAssertionException(
					$"Expected a freshly provisioned key to be usable for encryption, but its status is {created.Status}.");
			}

			var readBack = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			if (readBack is null)
			{
				throw new TestFixtureAssertionException(
					"CreateKeyIfAbsentAsync returned metadata for a key the provider does not hold. The returned "
					+ "metadata must describe what the backend actually stores, not what the call attempted.");
			}

			var successor = await provider
				.GetKeyVersionAsync(keyId, created.Version + 1, CancellationToken.None).ConfigureAwait(false);

			if (successor is not null)
			{
				throw new TestFixtureAssertionException(
					$"Provisioning one key produced more than one version: version {created.Version + 1} also exists.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that provisioning a key that already exists changes nothing.
	/// </summary>
	/// <remarks>
	/// <para>
	/// SAFETY, and the heart of the contract. A get-or-create built on a create-OR-rotate operation retires
	/// the live version whenever the key turns out to be present -- and any status other than Active is
	/// refused for encryption, so the caller ends up with ciphertext written under a version the store has
	/// fenced, and a key nobody asked to rotate. RED input: a second call for an existing key.
	/// </para>
	/// <para>
	/// This arm asserts what every backend can promise. It does NOT assert a version COUNT, because a store
	/// whose only create operation also adds a version cannot promise that; it asserts that the version which
	/// was there before is still there and still Active, which every backend can.
	/// </para>
	/// </remarks>
	public virtual async Task CreateKeyIfAbsentAsync_WhenPresent_ShouldNotRotateOrDemote()
	{
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			var first = await provider
				.CreateKeyIfAbsentAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, CancellationToken.None)
				.ConfigureAwait(false);

			var second = await provider
				.CreateKeyIfAbsentAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, CancellationToken.None)
				.ConfigureAwait(false);

			if (!string.Equals(second.KeyId, first.KeyId, StringComparison.Ordinal))
			{
				throw new TestFixtureAssertionException(
					$"Provisioning an existing key returned a different handle: '{second.KeyId}' rather than '{first.KeyId}'.");
			}

			var original = await provider
				.GetKeyVersionAsync(keyId, first.Version, CancellationToken.None).ConfigureAwait(false);

			if (original is null)
			{
				throw new TestFixtureAssertionException(
					$"Version {first.Version} no longer exists after a second provisioning call. This operation must "
					+ "not remove or replace a version that was already there.");
			}

			if (original.Status != KeyStatus.Active)
			{
				throw new TestFixtureAssertionException(
					$"A second provisioning call demoted version {first.Version} to {original.Status}. This is not a "
					+ "rotation: a caller asking for a key to exist has not asked to retire the key that does.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that concurrent first provisionings of one key do not demote each other.
	/// </summary>
	/// <remarks>
	/// <para>
	/// SAFETY under concurrency, and the arm that RED-detects the original defect. Two ordinary first writes
	/// for one new subject were enough: each read "absent", and the one that wrote second found the key
	/// present and rotated it, retiring the version the first had just created. No rotation was requested by
	/// anyone and no unusual configuration was involved.
	/// </para>
	/// <para>
	/// Every caller must come away with the SAME key, and a lost race must be a no-op rather than an error.
	/// A provider whose backend cannot create without adding a version may leave extra versions behind -- that
	/// is permitted and is why this arm does not count them -- but no backend may demote one.
	/// </para>
	/// </remarks>
	public virtual async Task CreateKeyIfAbsentAsync_ConcurrentFirstWrites_ShouldNotDemoteEachOther()
	{
		const int Writers = 4;

		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			using var start = new SemaphoreSlim(0, Writers);

			var races = new Task<KeyMetadata>[Writers];
			for (var i = 0; i < Writers; i++)
			{
				races[i] = Task.Run(async () =>
				{
					await start.WaitAsync(CancellationToken.None).ConfigureAwait(false);

					return await provider
						.CreateKeyIfAbsentAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, CancellationToken.None)
						.ConfigureAwait(false);
				});
			}

			// Released together so the writers overlap, which is what makes the race reachable at all.
			start.Release(Writers);

			var results = await Task.WhenAll(races).ConfigureAwait(false);

			foreach (var result in results)
			{
				if (!string.Equals(result.KeyId, keyId, StringComparison.Ordinal))
				{
					throw new TestFixtureAssertionException(
						$"A concurrent provisioning returned handle '{result.KeyId}' instead of '{keyId}'.");
				}
			}

			// Whatever versions exist, every one of them must still be usable. A demotion is the harm.
			var highest = results.Max(static r => r.Version);

			for (var version = results.Min(static r => r.Version); version <= highest; version++)
			{
				var observed = await provider
					.GetKeyVersionAsync(keyId, version, CancellationToken.None).ConfigureAwait(false);

				if (observed is not null && observed.Status != KeyStatus.Active)
				{
					throw new TestFixtureAssertionException(
						$"Concurrent first provisionings left version {version} as {observed.Status}. One writer "
						+ "rotated the key another had just created, so a key nobody asked to retire was retired "
						+ "and encryption under it is now refused.");
				}
			}

			var current = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			if (current is null || current.Status != KeyStatus.Active)
			{
				throw new TestFixtureAssertionException(
					"After concurrent provisioning the key must exist with a usable current version, but it is "
					+ (current is null ? "absent." : $"{current.Status}."));
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region DeleteKey Tests

	/// <summary>
	/// Verifies that DeleteKeyAsync returns false for non-existent key.
	/// </summary>
	public virtual async Task DeleteKeyAsync_NonExistent_ShouldReturnFalse()
	{
		// Arrange
		var admin = CreateAdmin();
		try
		{
			// Act
			var result = await admin.DeleteKeyAsync("non-existent-key", 30, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result.State != KeyDestructionState.NotFound)
			{
				throw new TestFixtureAssertionException(
					"Expected DeleteKeyAsync to report NotFound for a non-existent key.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(admin as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that DeleteKeyAsync schedules key for deletion (crypto-shredding).
	/// </summary>
	public virtual async Task DeleteKeyAsync_ExistingKey_ShouldScheduleForDestruction()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId = GenerateKeyId();

			// Create key
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Act
			var result = await admin.DeleteKeyAsync(keyId, 30, CancellationToken.None).ConfigureAwait(false);

			// Assert — an existing key must be destroyed or scheduled, never reported NotFound.
			if (result.State == KeyDestructionState.NotFound)
			{
				throw new TestFixtureAssertionException("Expected DeleteKeyAsync to destroy or schedule an existing key.");
			}

			// Branch on the outcome the contract actually defines. DeleteKeyAsync documents TWO legal
			// results, and demanding only one of them rejects a correct implementation: a backend that
			// destroys key material immediately -- Vault Transit, most HSMs -- returns Completed, and the
			// key is then correctly gone. Requiring it to linger as PendingDestruction failed such a
			// provider for being right, and this kit ships, so that verdict reaches consumers writing
			// their own provider.
			var metadata = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			if (result.State == KeyDestructionState.ScheduledIrreversible)
			{
				// Scheduled means recoverable until the window elapses, so the key must remain observable --
				// otherwise destruction cannot be attested, which is the whole point of the distinction.
				if (metadata is null)
				{
					throw new TestFixtureAssertionException(
						"Expected a scheduled key to remain observable until its window elapses.");
				}

				if (metadata.Status != KeyStatus.PendingDestruction)
				{
					throw new TestFixtureAssertionException(
						$"Expected key status to be PendingDestruction, but got {metadata.Status}.");
				}
			}
			else if (metadata is not null && metadata.Status is not (KeyStatus.Destroyed or KeyStatus.PendingDestruction))
			{
				// Completed means the material is already irrecoverable. The key may be absent, or present
				// and reported destroyed; what it must not be is still usable.
				throw new TestFixtureAssertionException(
					$"Expected a completed destruction to leave the key unusable, but its status is {metadata.Status}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that <see cref="IKeyDestructionStatusProvider.IsKeyDestroyedAsync(string, System.Threading.CancellationToken)"/> AGREES with the outcome
	/// the destruction reported, for the zero-retention destruction the erasure path actually performs.
	/// </summary>
	/// <remarks>
	/// <para>
	/// <b>Why this arm exists.</b> This capability is the sole gate on certifying an erasure: the verification
	/// service asks it, and a provider that does not advertise it never has its erasures certified. Until this
	/// arm, nothing in this kit called it at all -- so a provider could pass every published arm and still
	/// answer the attestation question wrongly, at which point an erasure that did not happen is certified to
	/// a data subject. That is the severe direction, and it is why this arm ships in the kit rather than
	/// living in one provider's own tests.
	/// </para>
	/// <para>
	/// <b>Zero retention is the point, not an incidental argument.</b> The erasure calls
	/// <c>DeleteKeyAsync(keyId, 0, ct)</c>, and providers BRANCH on that: a retention of zero destroys
	/// outright where a positive retention schedules. The other arms in this region pass 30, so they exercise
	/// the branch production never takes.
	/// </para>
	/// <para>
	/// <b>The assertion is AGREEMENT, not a fixed answer, and that is deliberate.</b> Requiring
	/// <see langword="true"/> here would fail a correct provider: a backend with a mandatory minimum deletion
	/// window clamps a zero retention up to that minimum and reports the destruction as scheduled, and while
	/// it is scheduled the material is still recoverable -- so <see langword="false"/> is the honest answer
	/// and certifying it would be the defect. What must never happen is the pair disagreeing: a destruction
	/// reported complete whose material this reports as still recoverable, or a still-recoverable key
	/// reported destroyed.
	/// </para>
	/// </remarks>
	public virtual async Task IsKeyDestroyedAsync_AfterZeroRetentionDelete_ShouldAgreeWithTheReportedOutcome()
	{
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var status = RequireDestructionStatusProvider(provider);
			var keyId = GenerateKeyId();

			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Guard: the key must really be live before it is destroyed, or a provider that answers "destroyed"
			// to everything would satisfy the assertion below without ever destroying anything.
			if (await status.IsKeyDestroyedAsync(keyId, CancellationToken.None).ConfigureAwait(false))
			{
				throw new TestFixtureAssertionException(
					"A key that was just created is reported destroyed. Either creation did not take effect or "
					+ "IsKeyDestroyedAsync answers true unconditionally; either way an erasure could be certified "
					+ "for a key that still holds material.");
			}

			// The retention the erasure itself passes.
			var outcome = await admin.DeleteKeyAsync(keyId, 0, CancellationToken.None).ConfigureAwait(false);

			if (outcome.State == KeyDestructionState.NotFound)
			{
				throw new TestFixtureAssertionException(
					"Expected a zero-retention delete of an existing key to destroy or schedule it, not report NotFound.");
			}

			var destroyed = await status.IsKeyDestroyedAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			if (outcome.State == KeyDestructionState.Completed && !destroyed)
			{
				throw new TestFixtureAssertionException(
					"DeleteKeyAsync reported the destruction COMPLETED but IsKeyDestroyedAsync reports the material "
					+ "as still recoverable. These two answers gate the same certification, so a disagreement means "
					+ "an erasure is attested on evidence the provider itself contradicts.");
			}

			if (outcome.State == KeyDestructionState.ScheduledIrreversible && destroyed)
			{
				throw new TestFixtureAssertionException(
					"DeleteKeyAsync reported the destruction as SCHEDULED -- so the material is still recoverable "
					+ "until the window elapses -- but IsKeyDestroyedAsync reports it destroyed. Certifying that "
					+ "would tell a data subject their data is unreadable while it can still be recovered.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(admin as IDisposable)?.Dispose();
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that <see cref="IKeyDestructionStatusProvider.IsKeyDestroyedAsync(string, System.Threading.CancellationToken)"/> reports a live key as NOT
	/// destroyed.
	/// </summary>
	/// <remarks>
	/// The anti-cheat twin of the arm above, and the reason that one cannot be satisfied trivially. A provider
	/// that answers <see langword="true"/> unconditionally would certify every erasure it was ever asked
	/// about, including ones that destroyed nothing -- so the capability needs an arm that fails for it. A key
	/// that has been created and never deleted is the input.
	/// </remarks>
	public virtual async Task IsKeyDestroyedAsync_ForALiveKey_ShouldReportNotDestroyed()
	{
		var provider = CreateProvider();
		try
		{
			var status = RequireDestructionStatusProvider(provider);
			var keyId = GenerateKeyId();

			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Guard: the key must be observable, so a provider whose creation silently failed cannot reach the
			// assertion below and pass it for the wrong reason.
			var metadata = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			if (metadata is null)
			{
				throw new TestFixtureAssertionException(
					"The key under test was not observable after creation, so this arm cannot establish anything "
					+ "about a LIVE key.");
			}

			if (await status.IsKeyDestroyedAsync(keyId, CancellationToken.None).ConfigureAwait(false))
			{
				throw new TestFixtureAssertionException(
					"IsKeyDestroyedAsync reports a live, never-deleted key as destroyed. This capability is the sole "
					+ "gate on certifying an erasure, so answering true here certifies erasures that never happened.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that a key deleted but still RECOVERABLE is reported as NOT destroyed.
	/// </summary>
	/// <remarks>
	/// <para>
	/// <b>This is the arm the absence-as-destruction defect fails.</b> The two arms above exercise the
	/// zero-retention destruction the erasure path performs; this one exercises the positive-retention delete,
	/// which on a soft-deleting backend leaves the material recoverable for the whole retention window. A
	/// provider that derives its answer from a key LOOKUP rather than from a statement about recoverability
	/// answers <see langword="true"/> here -- Azure Key Vault, for instance, answers a soft-deleted key as not
	/// found for that entire window -- and certifying on that attests an erasure over data the vault can still
	/// hand back.
	/// </para>
	/// <para>
	/// <b>The gate is the reported outcome, not the retention we passed.</b> A backend with no recovery window
	/// destroys outright whatever retention it is given and reports <c>Completed</c>; for such a provider
	/// <see langword="true"/> is the honest answer and this arm has nothing to assert, so it asserts nothing
	/// and says so. The arm binds precisely where a recovery window exists, which is where the defect lives.
	/// </para>
	/// </remarks>
	/// <returns> A task representing the arm. </returns>
	public virtual async Task IsKeyDestroyedAsync_WhileStillRecoverable_ShouldReportNotDestroyed()
	{
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var status = RequireDestructionStatusProvider(provider);
			var keyId = GenerateKeyId();

			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			var outcome = await admin.DeleteKeyAsync(keyId, 30, CancellationToken.None).ConfigureAwait(false);

			if (outcome.State == KeyDestructionState.NotFound)
			{
				throw new TestFixtureAssertionException(
					"Expected a retained delete of an existing key to destroy or schedule it, not report NotFound.");
			}

			if (outcome.State != KeyDestructionState.ScheduledIrreversible)
			{
				// No recovery window on this backend: the material really is gone, so there is no recoverable
				// state for this arm to be about.
				SkipArm(
					nameof(IsKeyDestroyedAsync_WhileStillRecoverable_ShouldReportNotDestroyed),
					null,
					"The backend reported the destruction as "
					+ outcome.State.ToString()
					+ " for a 30-day retention, so it holds no recoverable copy and has no recovery window for "
					+ "this arm to examine.");
				return;
			}

			RecordArmExecuted(nameof(IsKeyDestroyedAsync_WhileStillRecoverable_ShouldReportNotDestroyed));

			if (await status.IsKeyDestroyedAsync(keyId, CancellationToken.None).ConfigureAwait(false))
			{
				throw new TestFixtureAssertionException(
					"The destruction was reported as SCHEDULED -- the backend can still restore this key -- and "
					+ "IsKeyDestroyedAsync reports it destroyed. Answering from a key lookup produces exactly this: "
					+ "a soft-deleted key is invisible to the lookup for its whole retention window, so absence is "
					+ "read as destruction and an erasure is certified over recoverable personal data.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(admin as IDisposable)?.Dispose();
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that a key's GENERATION does not move across a rotation.
	/// </summary>
	/// <remarks>
	/// <para>
	/// A rotation extends one material lineage, so the generation identifies the lineage and must be the same
	/// before and after. The destruction record holds the generation found when the erasure ran; if a rotation
	/// changed it, every envelope written before that rotation would name an identifier no record will ever
	/// hold, and its read would fail permanently -- the material destroyed, and the identifier that would have
	/// recorded it unreadable, so no retry can repair it.
	/// </para>
	/// <para>
	/// <b>This is the arm that fails a provider reusing a backend per-version value.</b> An opaque key-vault
	/// version id and a per-version key ARN both change on rotation while looking like perfectly good
	/// identifiers, and nothing else in this kit notices.
	/// </para>
	/// </remarks>
	/// <returns> A task representing the arm. </returns>
	public virtual async Task Generation_ShouldBeStable_AcrossARotation()
	{
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			var first = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);
			var before = first?.Generation;

			if (before is null)
			{
				SkipArm(
					nameof(Generation_ShouldBeStable_AcrossARotation),
					null,
					"The provider reports no generation on a key it just provisioned, so it cannot support a "
					+ "crypto-shred read path and there is no lineage identity for this arm to examine.");
				return;
			}

			RecordArmExecuted(nameof(Generation_ShouldBeStable_AcrossARotation));

			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			var rotated = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			// Guard: the rotation must actually have produced a new version, or "unchanged" is satisfied by
			// nothing having happened.
			if (rotated is null || rotated.Version <= first!.Version)
			{
				throw new TestFixtureAssertionException(
					"The second rotation did not advance the version, so this arm cannot establish that the "
					+ "generation survives one. A provider whose rotation is a no-op would pass the comparison "
					+ "below without ever rotating.");
			}

			// Compared as generations, not as strings. The type's equality is ordinal by construction, so an
			// arm cannot accidentally compare case-insensitively and pass over two different records.
			if (before != rotated.Generation)
			{
				throw new TestFixtureAssertionException(
					"The generation CHANGED across a rotation. A rotation extends one material lineage, so every "
					+ "envelope written before it still names the generation reported earlier. An erasure records "
					+ "only the generation present when it runs, so those envelopes would name an identifier no "
					+ "destruction record holds, and their reads would fail permanently with no repair available. "
					+ "A backend per-version identifier -- an opaque version id, a per-version key ARN -- is not a "
					+ "lineage identifier and must not be reported as the generation.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that a handle re-provisioned after a COMPLETED destruction reports a DIFFERENT generation.
	/// </summary>
	/// <remarks>
	/// <para>
	/// The twin of the arm above, failing the opposite defect. A handle is derived from the data subject, so it
	/// is stable and gets re-occupied: destroy a subject's key and let an ordinary write provision another at
	/// the same handle. If the generation stayed the same, the destroyed generation's record would match the NEW
	/// material, and every field written after the erasure would be reported as lawfully erased while being
	/// perfectly readable -- a tombstone over live personal data, which is the catastrophic direction.
	/// </para>
	/// <para>
	/// Without this arm, the stability arm above is satisfied by a provider returning one constant for every key
	/// it ever holds.
	/// </para>
	/// </remarks>
	/// <returns> A task representing the arm. </returns>
	public virtual async Task Generation_ShouldChange_WhenAHandleIsReprovisionedAfterDestruction()
	{
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId = GenerateKeyId();

			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			var destroyedGeneration =
				(await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false))?.Generation;

			if (destroyedGeneration is null)
			{
				SkipArm(
					nameof(Generation_ShouldChange_WhenAHandleIsReprovisionedAfterDestruction),
					null,
					"The provider reports no generation on a key it just provisioned, so there is no lineage "
					+ "identity for this arm to examine.");
				return;
			}

			var outcome = await admin.DeleteKeyAsync(keyId, 0, CancellationToken.None).ConfigureAwait(false);

			if (outcome.State != KeyDestructionState.Completed)
			{
				// The handle is not free yet. A backend with a mandatory recovery window cannot be
				// re-provisioned at the same name until it elapses, so the state this arm is about is
				// unreachable here rather than untested.
				SkipArm(
					nameof(Generation_ShouldChange_WhenAHandleIsReprovisionedAfterDestruction),
					null,
					"A zero-retention delete reported "
					+ outcome.State.ToString()
					+ " rather than Completed, so the handle cannot be re-provisioned yet and the re-occupation "
					+ "this arm examines is unreachable on this backend.");
				return;
			}

			RecordArmExecuted(nameof(Generation_ShouldChange_WhenAHandleIsReprovisionedAfterDestruction));

			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			var reprovisioned =
				(await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false))?.Generation;

			if (reprovisioned is null)
			{
				throw new TestFixtureAssertionException(
					"The handle was re-provisioned but reports no generation, so no field written under the new "
					+ "key can ever be read once a destruction is recorded against this handle.");
			}

			if (destroyedGeneration == reprovisioned)
			{
				throw new TestFixtureAssertionException(
					"A handle re-provisioned after a COMPLETED destruction reports the SAME generation as the "
					+ "material that was destroyed. The destroyed generation's record then matches this new key, "
					+ "so every field written under it is reported as lawfully erased while remaining perfectly "
					+ "readable -- a tombstone asserted over live personal data. A generation must identify the "
					+ "MATERIAL, never the handle: handles are derived from the data subject and are re-occupied "
					+ "by design.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(admin as IDisposable)?.Dispose();
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Resolves the destruction-status capability, failing with an explanation rather than skipping.
	/// </summary>
	/// <param name="provider">The provider under test.</param>
	/// <returns>The provider's destruction-status capability.</returns>
	/// <remarks>
	/// Fails rather than passing when the capability is absent, because a silent pass is how an unmet
	/// obligation becomes invisible. A provider that genuinely cannot answer -- one whose backend exposes no
	/// way to tell a destroyed key from a live one -- should mark these two arms skipped in its own suite, with
	/// the reason: its erasures are then never certified, which is the correct outcome and worth being able to
	/// see. What must not happen is these arms reporting green for a provider that never ran them.
	/// </remarks>
	private static IKeyDestructionStatusProvider RequireDestructionStatusProvider(IKeyManagementProvider provider)
	{
		ArgumentNullException.ThrowIfNull(provider);

		if (provider is IKeyDestructionStatusProvider direct)
		{
			return direct;
		}

		if (provider.GetService(typeof(IKeyDestructionStatusProvider)) is IKeyDestructionStatusProvider resolved)
		{
			return resolved;
		}

		throw new TestFixtureAssertionException(
			$"{provider.GetType().Name} does not supply IKeyDestructionStatusProvider, so no erasure using it can "
			+ "ever be certified -- the verification service treats the missing capability as fail-closed. If that "
			+ "is intended for this provider, mark these arms skipped in your suite with that reason so the gap "
			+ "stays visible; a decorator that merely forgot to forward GetService should forward it.");
	}

	#endregion

	#region SuspendKey Tests

	/// <summary>
	/// Verifies that SuspendKeyAsync returns false for non-existent key.
	/// </summary>
	public virtual async Task SuspendKeyAsync_NonExistent_ShouldReturnFalse()
	{
		// Arrange
		var admin = CreateAdmin();
		try
		{
			// Act
			var result = await admin.SuspendKeyAsync("non-existent-key", "security-reason", CancellationToken.None)
				.ConfigureAwait(false);

			// Assert
			if (result)
			{
				throw new TestFixtureAssertionException(
					"Expected SuspendKeyAsync to return false for non-existent key.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(admin as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that SuspendKeyAsync suspends all versions of a key.
	/// </summary>
	public virtual async Task SuspendKeyAsync_ExistingKey_ShouldSuspendAllVersions()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId = GenerateKeyId();

			// Create key and rotate to have multiple versions
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Act
			var result = await admin.SuspendKeyAsync(keyId, "security-incident", CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (!result)
			{
				throw new TestFixtureAssertionException("Expected SuspendKeyAsync to return true.");
			}

			// Verify all versions are suspended
			var v1Metadata = await provider.GetKeyVersionAsync(keyId, 1, CancellationToken.None).ConfigureAwait(false);
			var v2Metadata = await provider.GetKeyVersionAsync(keyId, 2, CancellationToken.None).ConfigureAwait(false);

			if (v1Metadata is null || v2Metadata is null)
			{
				throw new TestFixtureAssertionException("Expected both versions to exist.");
			}

			if (v1Metadata.Status != KeyStatus.Suspended)
			{
				throw new TestFixtureAssertionException(
					$"Expected version 1 to be Suspended, but got {v1Metadata.Status}.");
			}

			if (v2Metadata.Status != KeyStatus.Suspended)
			{
				throw new TestFixtureAssertionException(
					$"Expected version 2 to be Suspended, but got {v2Metadata.Status}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that SuspendKeyAsync throws for null/empty reason.
	/// </summary>
	public virtual async Task SuspendKeyAsync_NullReason_ShouldThrowArgumentException()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId = GenerateKeyId();
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Act & Assert
			var caughtException = false;
			try
			{
				_ = await admin.SuspendKeyAsync(keyId, null!, CancellationToken.None).ConfigureAwait(false);
			}
			catch (ArgumentException)
			{
				caughtException = true;
			}

			if (!caughtException)
			{
				throw new TestFixtureAssertionException(
					"Expected SuspendKeyAsync to throw ArgumentException for null reason.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region ReactivateKey Tests

	/// <summary>
	/// Verifies that ReactivateKeyAsync returns false for a non-existent key.
	/// </summary>
	public virtual async Task ReactivateKeyAsync_NonExistent_ShouldReturnFalse()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			// Act
			var result = await admin.ReactivateKeyAsync("non-existent-key", CancellationToken.None)
				.ConfigureAwait(false);

			// Assert
			if (result)
			{
				throw new TestFixtureAssertionException(
					"Expected ReactivateKeyAsync to return false for non-existent key.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that ReactivateKeyAsync restores a suspended key to usable/active state — the
	/// inverse of SuspendKeyAsync. Suspend renders the key unusable (excluded from GetActiveKey);
	/// reactivate must make it active and usable again.
	/// </summary>
	public virtual async Task ReactivateKeyAsync_SuspendedKey_ShouldRestoreToActive()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId = GenerateKeyId();
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, "encryption", null, CancellationToken.None)
				.ConfigureAwait(false);

			// Suspend → the key must become unusable (absent from the active key set).
			_ = await admin.SuspendKeyAsync(keyId, "security-incident", CancellationToken.None).ConfigureAwait(false);

			var suspendedMetadata = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);
			if (suspendedMetadata is null || suspendedMetadata.Status != KeyStatus.Suspended)
			{
				throw new TestFixtureAssertionException(
					$"Expected key to be Suspended after SuspendKeyAsync, but got {suspendedMetadata?.Status.ToString() ?? "null"}.");
			}

			// Act — reactivate.
			var result = await admin.ReactivateKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (!result)
			{
				throw new TestFixtureAssertionException("Expected ReactivateKeyAsync to return true for an existing key.");
			}

			var reactivatedMetadata = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);
			if (reactivatedMetadata is null || reactivatedMetadata.Status != KeyStatus.Active)
			{
				throw new TestFixtureAssertionException(
					$"Expected key to be Active after ReactivateKeyAsync, but got {reactivatedMetadata?.Status.ToString() ?? "null"}.");
			}

			// The reactivated key must be usable again — surfaced by GetActiveKeyAsync.
			var activeKey = await provider.GetActiveKeyAsync("encryption", CancellationToken.None).ConfigureAwait(false);
			if (activeKey is null || activeKey.KeyId != keyId)
			{
				throw new TestFixtureAssertionException(
					"Expected GetActiveKeyAsync to return the reactivated key.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region GetActiveKey Tests

	/// <summary>
	/// Verifies that GetActiveKeyAsync returns null when no active key exists.
	/// </summary>
	public virtual async Task GetActiveKeyAsync_NoActiveKey_ShouldReturnNull()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			// Act
			var result = await provider.GetActiveKeyAsync(null, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is not null)
			{
				throw new TestFixtureAssertionException(
					"Expected GetActiveKeyAsync to return null when no active key exists.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that GetActiveKeyAsync returns the active key.
	/// </summary>
	public virtual async Task GetActiveKeyAsync_ActiveKeyExists_ShouldReturnActiveKey()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			var keyId = GenerateKeyId();

			// Create key
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);

			// Act
			var result = await provider.GetActiveKeyAsync(null, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is null)
			{
				throw new TestFixtureAssertionException("Expected GetActiveKeyAsync to return an active key.");
			}

			if (result.KeyId != keyId)
			{
				throw new TestFixtureAssertionException(
					$"Expected active key to be {keyId}, but got {result.KeyId}.");
			}

			if (result.Status != KeyStatus.Active)
			{
				throw new TestFixtureAssertionException(
					$"Expected key status to be Active, but got {result.Status}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that GetActiveKeyAsync filters by purpose.
	/// </summary>
	public virtual async Task GetActiveKeyAsync_FilterByPurpose_ShouldFilterCorrectly()
	{
		// Arrange
		var provider = CreateProvider();
		try
		{
			var keyId1 = GenerateKeyId();
			var keyId2 = GenerateKeyId();

			// Create keys with different purposes
			_ = await provider.RotateKeyAsync(keyId1, EncryptionAlgorithm.Aes256Gcm, "encryption", null, CancellationToken.None)
				.ConfigureAwait(false);
			_ = await provider.RotateKeyAsync(keyId2, EncryptionAlgorithm.Aes256Gcm, "signing", null, CancellationToken.None)
				.ConfigureAwait(false);

			// Act
			var result = await provider.GetActiveKeyAsync("signing", CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is null)
			{
				throw new TestFixtureAssertionException("Expected GetActiveKeyAsync to return a key.");
			}

			if (result.KeyId != keyId2)
			{
				throw new TestFixtureAssertionException(
					$"Expected key with purpose 'signing' to be {keyId2}, but got {result.KeyId}.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	/// <summary>
	/// Verifies that GetActiveKeyAsync skips suspended keys.
	/// </summary>
	public virtual async Task GetActiveKeyAsync_SuspendedKey_ShouldNotReturn()
	{
		// Arrange
		var provider = CreateProvider();
		var admin = (provider is IKeyManagementAdmin a) ? a : CreateAdmin();
		try
		{
			var keyId = GenerateKeyId();

			// Create and suspend key
			_ = await provider.RotateKeyAsync(keyId, EncryptionAlgorithm.Aes256Gcm, null, null, CancellationToken.None)
				.ConfigureAwait(false);
			_ = await admin.SuspendKeyAsync(keyId, "test-suspension", CancellationToken.None).ConfigureAwait(false);

			// Act
			var result = await provider.GetActiveKeyAsync(null, CancellationToken.None).ConfigureAwait(false);

			// Assert
			if (result is not null)
			{
				throw new TestFixtureAssertionException(
					"Expected GetActiveKeyAsync to return null for suspended key.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
			(provider as IDisposable)?.Dispose();
		}
	}

	#endregion

	#region Disposable Tests

	/// <summary>
	/// Verifies that disposed provider throws ObjectDisposedException.
	/// </summary>
	public virtual async Task Disposed_Provider_ShouldThrowObjectDisposedException()
	{
		// Arrange
		var provider = CreateProvider();
		var keyId = GenerateKeyId();

		try
		{
			// Dispose if IDisposable
			(provider as IDisposable)?.Dispose();

			// Act & Assert
			var caughtException = false;
			try
			{
				_ = await provider.GetKeyAsync(keyId, CancellationToken.None).ConfigureAwait(false);
			}
			catch (ObjectDisposedException)
			{
				caughtException = true;
			}

			// Note: Only IDisposable implementations are required to throw
			// Non-disposable implementations may not support this pattern
			if (provider is IDisposable && !caughtException)
			{
				throw new TestFixtureAssertionException(
					"Expected disposed provider to throw ObjectDisposedException.");
			}
		}
		finally
		{
			await CleanupAsync().ConfigureAwait(false);
		}
	}

	#endregion

}
