// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0


using System.Text.Json.Serialization;

using RabbitMQ.Client;
using RabbitMQ.Client.Events;

namespace Excalibur.Dispatch.Transport.RabbitMQ;

/// <summary>
/// Source generation context for RabbitMQ message types. Provides AOT-compatible JSON serialization for AMQP messaging.
/// </summary>
/// <remarks>
/// This context is optimized for RabbitMQ/AMQP messaging with:
/// - AMQP basic properties serialization
/// - Exchange and routing key support
/// - Dead letter exchange handling
/// - Priority queue support.
/// </remarks>
[JsonSourceGenerationOptions(
	PropertyNameCaseInsensitive = true,
	WriteIndented = false,
	DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
	GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization,
	PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
	UseStringEnumConverter = true)]

// RabbitMQ message types
[JsonSerializable(typeof(BasicDeliverEventArgs))]
[JsonSerializable(typeof(IBasicProperties))]
[JsonSerializable(typeof(BasicProperties))]
[JsonSerializable(typeof(ReadOnlyMemory<byte>))]

// AMQP properties and headers
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(IDictionary<string, object>))]
[JsonSerializable(typeof(AmqpTimestamp))]
[JsonSerializable(typeof(PublicationAddress))]

// Exchange and queue this.configuration
[JsonSerializable(typeof(ExchangeConfiguration))]
[JsonSerializable(typeof(QueueConfiguration))]
[JsonSerializable(typeof(BindingConfiguration))]
[JsonSerializable(typeof(List<BindingConfiguration>))]

// Consumer and channel this.state
[JsonSerializable(typeof(ConsumerState))]
[JsonSerializable(typeof(ChannelState))]
[JsonSerializable(typeof(ConnectionState))]

// Dead letter and retry
[JsonSerializable(typeof(DeadLetterConfiguration))]
[JsonSerializable(typeof(RetryConfiguration))]
[JsonSerializable(typeof(List<RetryAttempt>))]

// Message routing
[JsonSerializable(typeof(RoutingInfo))]
[JsonSerializable(typeof(List<RoutingInfo>))]
[JsonSerializable(typeof(Dictionary<string, RoutingInfo>))]

// Common types
[JsonSerializable(typeof(byte[]))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(ulong))]
[JsonSerializable(typeof(Guid))]
public partial class RabbitMqMessageJsonContext : JsonSerializerContext
{
	// The Default property is generated by the source generator No need to define it manually
}
