// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0


using System.Text.Json.Serialization;

using Confluent.Kafka;

namespace Excalibur.Dispatch.Transport.Kafka;

/// <summary>
/// Source generation context for Kafka message types. Provides AOT-compatible JSON serialization for Kafka messaging.
/// </summary>
/// <remarks>
/// This context is optimized for Kafka messaging with:
/// - High-throughput batch processing
/// - Partition-aware serialization
/// - Header metadata support
/// - Consumer group coordination.
/// </remarks>
[JsonSourceGenerationOptions(
	PropertyNameCaseInsensitive = true,
	WriteIndented = false,
	DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
	GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization,
	PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
	UseStringEnumConverter = true)]

// Kafka message types
[JsonSerializable(typeof(Message<string, string>))]
[JsonSerializable(typeof(Message<string, byte[]>))]
[JsonSerializable(typeof(Message<byte[], byte[]>))]
[JsonSerializable(typeof(ConsumeResult<string, string>))]
[JsonSerializable(typeof(ConsumeResult<string, byte[]>))]
[JsonSerializable(typeof(ConsumeResult<byte[], byte[]>))]
[JsonSerializable(typeof(DeliveryResult<string, string>))]
[JsonSerializable(typeof(DeliveryResult<string, byte[]>))]
[JsonSerializable(typeof(DeliveryResult<byte[], byte[]>))]

// Kafka headers and metadata
[JsonSerializable(typeof(Headers))]
[JsonSerializable(typeof(Header))]
[JsonSerializable(typeof(Dictionary<string, byte[]>))]
[JsonSerializable(typeof(Dictionary<string, string>))]

// Partition and offset management
[JsonSerializable(typeof(TopicPartition))]
[JsonSerializable(typeof(TopicPartitionOffset))]
[JsonSerializable(typeof(List<TopicPartition>))]
[JsonSerializable(typeof(List<TopicPartitionOffset>))]
[JsonSerializable(typeof(WatermarkOffsets))]

// Consumer group coordination
// Note: ConsumerGroupMetadata is internal in Confluent.Kafka and cannot be serialized directly
[JsonSerializable(typeof(ConsumerGroupState))]
[JsonSerializable(typeof(PartitionAssignment))]
[JsonSerializable(typeof(List<PartitionAssignment>))]

// Batch processing
[JsonSerializable(typeof(KafkaBatch))]
[JsonSerializable(typeof(List<KafkaMessage>))]
[JsonSerializable(typeof(BatchMetadata))]

// Common types
[JsonSerializable(typeof(byte[]))]
[JsonSerializable(typeof(ReadOnlyMemory<byte>))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(Timestamp))]
public partial class KafkaMessageJsonContext : JsonSerializerContext
{
	// The Default property is generated by the source generator No need to define it manually
}
