// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using Excalibur.Dispatch.Compliance;

namespace Excalibur.Dispatch.AuditLogging.Alerting;

/// <summary>
/// Defines a rule that triggers an alert when an audit event matches a condition.
/// </summary>
public sealed class AuditAlertRule
{
	/// <summary>
	/// Gets or sets the unique name of this rule.
	/// </summary>
	public required string Name { get; init; }

	/// <summary>
	/// Gets or sets the condition that triggers the alert.
	/// </summary>
	public required Func<AuditEvent, bool> Condition { get; init; }

	/// <summary>
	/// Gets or sets the severity of alerts generated by this rule.
	/// </summary>
	public AuditAlertSeverity Severity { get; init; } = AuditAlertSeverity.Warning;

	/// <summary>
	/// Gets or sets the notification channel for this rule (e.g., "email", "webhook", "pagerduty").
	/// </summary>
	public string? NotificationChannel { get; init; }
}
