name: ✏️ Documentation Request
description: Suggest improvements or additions to the documentation.
title: "[DOCS]: "
labels:
    - documentation
body:
    - type: markdown
      attributes:
          value: |
              Suggest improvements or additions to the project's documentation.

    - type: input
      id: title
      attributes:
          label: Documentation Title
          description: Provide a brief title for the documentation request.
          placeholder: Enter the title of the documentation request
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Documentation Description
          description: Describe what documentation should be added or improved.
          placeholder: Enter details about the requested documentation
      validations:
          required: true

    - type: textarea
      id: additional_context
      attributes:
          label: Additional Context
          description: Provide any other details or context about the documentation request.

    - type: markdown
      attributes:
          value: >
              Thanks for contributing 🎉!
