name: Feature Request
description: Suggest a new feature or enhancement for Excalibur
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: dropdown
    id: package
    attributes:
      label: Target Package
      description: Which package should this feature be added to?
      options:
        - Excalibur.Dispatch (messaging/dispatching)
        - Excalibur.Dispatch.Abstractions (interfaces/contracts)
        - Excalibur.Domain (aggregates/entities)
        - Excalibur.Data.Abstractions (data access)
        - Excalibur.EventSourcing (event stores)
        - Excalibur.EventSourcing.SqlServer
        - Excalibur.Saga (process managers)
        - Excalibur.LeaderElection
        - New Package
        - Not Sure
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Functionality
        - Performance Improvement
        - Developer Experience
        - API Enhancement
        - Integration / Provider
        - Documentation
        - Tooling
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API (Optional)
      description: If you have ideas for the API surface, share them here.
      render: csharp
      placeholder: |
        // Example interface or usage
        public interface IMyFeature
        {
            Task DoSomethingAsync(CancellationToken ct);
        }

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this feature require breaking changes to existing APIs?
      options:
        - "No"
        - "Yes - Minor"
        - "Yes - Major"
        - "Not Sure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing this feature?
      options:
        - label: I would be willing to submit a PR for this feature
