name: 🤔 Question
description: Ask a question or seek clarification about the project.
title: "[QUESTION]: "
labels:
    - question
body:
    - type: markdown
      attributes:
          value: |
              Have a question about the project? Ask it here, and we'll do our best to provide an answer!

    - type: input
      id: title
      attributes:
          label: Question Title
          description: Provide a brief title for your question.
          placeholder: Enter your question title
      validations:
          required: true

    - type: textarea
      id: question_details
      attributes:
          label: Question Details
          description: Provide detailed context or information about your question.
          placeholder: Enter detailed question context
      validations:
          required: true

    - type: textarea
      id: additional_context
      attributes:
          label: Additional Context
          description: Add any other details or related information.

    - type: markdown
      attributes:
          value: >
              Thanks for contributing 🎉!
