// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0


namespace Excalibur.Domain.Concurrency;

/// <summary>
/// Represents an ETag, commonly used for resource versioning in concurrency scenarios.
/// </summary>
public interface IETag
{
	/// <summary>
	/// Gets or sets the incoming ETag value, typically provided by the client to indicate the version of a resource they are working with.
	/// </summary>
	/// <value>
	/// The incoming ETag value, typically provided by the client to indicate the version of a resource they are working with.
	/// </value>
	string? IncomingValue { get; set; }

	/// <summary>
	/// Gets or sets the outgoing ETag value, typically generated by the server to represent the current version of a resource.
	/// </summary>
	/// <value>
	/// The outgoing ETag value, typically generated by the server to represent the current version of a resource.
	/// </value>
	string? OutgoingValue { get; set; }
}
