// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0


using Excalibur.Dispatch.Abstractions;
using Excalibur.Dispatch.Abstractions.Validation;

namespace Excalibur.Dispatch.Validation.FluentValidation;

/// <summary>
/// Dispatches validation to the correct strongly-typed FluentValidation validators
/// without runtime reflection. Implementations are source-generated by
/// <c>Excalibur.Dispatch.SourceGenerators</c>.
/// </summary>
/// <remarks>
/// Register the generated implementation via DI so that
/// <see cref="AotFluentValidatorResolver"/> can discover it at runtime.
/// When no implementation is registered, <see cref="AotFluentValidatorResolver"/>
/// throws <see cref="InvalidOperationException"/>.
/// </remarks>
public interface IAotValidationDispatcher
{
	/// <summary>
	/// Validates the given message by dispatching to the appropriate
	/// strongly-typed <c>IValidator&lt;T&gt;</c> resolved from DI.
	/// </summary>
	/// <param name="message">The message to validate.</param>
	/// <param name="provider">The service provider for resolving validators.</param>
	/// <returns>
	/// A <see cref="IValidationResult"/> if validators exist for the message type;
	/// <see langword="null"/> if no validators are registered for this message type.
	/// </returns>
	IValidationResult? TryValidate(IDispatchMessage message, IServiceProvider provider);
}
