// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using Excalibur.Dispatch.Compliance;
using Excalibur.Dispatch.Compliance.Diagnostics;
using Excalibur.Dispatch.Compliance.Encryption;

using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;

namespace Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Extension methods for configuring encryption services with the pluggable provider registry.
/// </summary>
public static class EncryptionServiceCollectionExtensions
{
	/// <summary>
	/// Adds the encryption provider registry and configures encryption services.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <param name="configure">Action to configure the encryption services using the fluent builder.</param>
	/// <returns>The service collection for chaining.</returns>
	/// <example>
	/// <code>
	/// services.AddEncryption(encryption => encryption
	///     .UseKeyManagement&lt;AesGcmEncryptionProvider&gt;("aes-gcm-primary")
	///     .ConfigureOptions(options => options.DefaultPurpose = "field-encryption"));
	/// </code>
	/// </example>
	public static IServiceCollection AddEncryption(
		this IServiceCollection services,
		Action<EncryptionConfigurationBuilder> configure)
	{
		ArgumentNullException.ThrowIfNull(services);
		ArgumentNullException.ThrowIfNull(configure);

		// Register the registry as a singleton.
		services.TryAddSingleton<IEncryptionProviderRegistry, EncryptionProviderRegistry>();

		// Create and execute the builder.
		var builder = new EncryptionConfigurationBuilder(services);
		configure(builder);

		// Validate that at least one provider was registered.
		builder.Validate();

		return services;
	}

	/// <summary>
	/// Adds development-only encryption services with an in-memory provider.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <returns>The service collection for chaining.</returns>
	/// <remarks>
	/// <para>
	/// <strong>WARNING:</strong> This method is for development and testing only.
	/// Do not use in production as keys are stored in memory and not persisted.
	/// </para>
	/// <para>
	/// A warning will be logged at startup to alert developers that this configuration
	/// is not suitable for production use.
	/// </para>
	/// </remarks>
	public static IServiceCollection AddDevEncryption(this IServiceCollection services)
	{
		ArgumentNullException.ThrowIfNull(services);

		// Register warning logger that fires on first resolution.
		_ = services.AddSingleton<DevEncryptionWarningLogger>();

		return services.AddEncryption(encryption => encryption
			.UseInMemoryKeyManagement("dev-inmemory", options =>
			{
				options.AutoGenerateDefaultKey = true;
			})
			.SetAsPrimary("dev-inmemory"));
	}

	/// <summary>
	/// Adds HKDF (RFC 5869) key derivation services.
	/// </summary>
	/// <param name="services">The service collection.</param>
	/// <param name="configure">Optional configuration for HKDF key derivation options.</param>
	/// <returns>The service collection for chaining.</returns>
	public static IServiceCollection AddHkdfKeyDerivation(
		this IServiceCollection services,
		Action<HkdfKeyDerivationOptions>? configure = null)
	{
		ArgumentNullException.ThrowIfNull(services);

		var optionsBuilder = services.AddOptions<HkdfKeyDerivationOptions>();
		if (configure is not null)
		{
			_ = optionsBuilder.Configure(configure);
		}

		services.TryAddSingleton<HkdfKeyDeriver>();

		return services;
	}
}

/// <summary>
/// Internal service to log warnings when dev encryption is used.
/// </summary>
internal sealed partial class DevEncryptionWarningLogger
{
	public DevEncryptionWarningLogger(ILogger<DevEncryptionWarningLogger> logger)
	{
		ArgumentNullException.ThrowIfNull(logger);

		LogDevEncryptionWarning(logger);
	}

	[LoggerMessage(ComplianceEventId.DevEncryptionWarning, LogLevel.Warning,
			"DEV ENCRYPTION IS ACTIVE. In-memory key management is being used. Keys are not persisted and will be lost on restart. Do NOT use this configuration in production. Configure a production key management provider using AddEncryption().")]
	private static partial void LogDevEncryptionWarning(ILogger logger);
}
