// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using Excalibur.Compliance;
using Excalibur.Compliance.Vault;

using Excalibur.Dispatch.Integration.Tests.Compliance.Fixtures;

using Excalibur.Testing.Conformance;

using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging.Abstractions;

namespace Excalibur.Dispatch.Integration.Tests.KeyManagement;

/// <summary>
/// Conformance tests binding <see cref="KeyManagementProviderConformanceTestKit"/> to the REAL
/// <see cref="VaultKeyProvider"/> against a real HashiCorp Vault dev container (see
/// <see cref="VaultContainerFixture"/>) — not a mock.
/// </summary>
/// <remarks>
/// <para>
/// <c>.claude/rules/process/verify-against-real-infra-not-mock.md</c> documents a real bug that shipped
/// in this exact seam: a mocked unit test for <c>SuspendKeyAsync</c> asserted only that an option value
/// was <em>sent</em>, never that Vault <em>accepted</em> it — real Vault rejected the value on its happy
/// path (bd-vihqw6). This deriver exists to keep the conformance kit's coverage of
/// <see cref="IKeyManagementProvider"/>/<see cref="IKeyManagementAdmin"/> from being certified only
/// against <see cref="InMemoryKeyManagementProvider"/> and never against Vault's real server-side
/// validation.
/// </para>
/// <para>
/// <b>Isolation without a fresh server per test:</b> the Vault dev container is shared across every test
/// in <see cref="VaultTestCollection"/>. <see cref="VaultKeyProvider.ListKeysAsync"/> filters Transit
/// keys by <see cref="VaultKeyOptions.KeyNamePrefix"/>, so <see cref="CreateProvider"/> mints a brand-new
/// random prefix on every call — each arm's provider instance is scoped to a Transit-key namespace no
/// other arm (or any other test class sharing this container) can see, which is what makes
/// <c>ListKeysAsync_NoKeys_ShouldReturnEmptyList</c> valid against a server that other tests are actively
/// writing to.
/// </para>
/// </remarks>
[Collection(VaultTestCollection.Name)]
[Trait("Category", "Integration")]
[Trait("Component", "Compliance")]
[Trait("Pattern", "PROVIDER")]
public sealed class VaultKeyManagementProviderConformanceTests : KeyManagementProviderConformanceTestKit, IDisposable
{
	private readonly VaultContainerFixture _fixture;
	private readonly List<IMemoryCache> _caches = [];

	public VaultKeyManagementProviderConformanceTests(VaultContainerFixture fixture) => _fixture = fixture;

	/// <inheritdoc />
	protected override IKeyManagementProvider CreateProvider()
	{
		_fixture.DockerAvailable.ShouldBeTrue(
			"KeyManagementProviderConformanceTestKit arms against VaultKeyProvider must run against real "
			+ "Vault -- never skipped. " + (_fixture.InitializationError ?? "Vault container required."));

		var cache = new MemoryCache(new MemoryCacheOptions());
		_caches.Add(cache);

		var vaultOptions = new VaultOptions
		{
			VaultUri = new Uri(_fixture.VaultAddress),
			Auth = { AuthMethod = VaultAuthMethod.Token, Token = _fixture.Token },
			// A fresh random prefix per provider instance scopes ListKeysAsync/GetActiveKeyAsync to keys
			// THIS instance created, so arms are isolated from each other and from the other test classes
			// sharing this Vault dev container (see remarks).
			Keys = new VaultKeyOptions { TransitMountPath = "transit", KeyNamePrefix = $"conformance-{Guid.NewGuid():N}-" },
			MetadataCacheDuration = TimeSpan.FromMinutes(5),
			// Suspension.MountPath defaults to "secret" -- the KV v2 engine the Vault dev container
			// auto-mounts. Suspension markers are keyed by raw keyId (GUID-generated by the kit's
			// GenerateKeyId()), so they do not collide across prefixes either.
		};

		return new VaultKeyProvider(
			Microsoft.Extensions.Options.Options.Create(vaultOptions),
			cache,
			NullLogger<VaultKeyProvider>.Instance);
	}

	public void Dispose()
	{
		foreach (var cache in _caches)
		{
			cache.Dispose();
		}
	}

	#region Suite wiring guard

	[Fact]
	public override Task ConformanceSuite_ShouldWireEveryArm() => base.ConformanceSuite_ShouldWireEveryArm();

	#endregion Suite wiring guard

	#region GetKey Tests

	[Fact]
	public Task GetKeyAsync_NonExistent_ShouldReturnNull_Test() =>
		GetKeyAsync_NonExistent_ShouldReturnNull();

	[Fact]
	public Task GetKeyAsync_NullKeyId_ShouldThrowArgumentException_Test() =>
		GetKeyAsync_NullKeyId_ShouldThrowArgumentException();

	[Fact]
	public Task GetKeyAsync_ExistingKey_ShouldReturnLatestVersion_Test() =>
		GetKeyAsync_ExistingKey_ShouldReturnLatestVersion();

	#endregion GetKey Tests

	#region GetKeyVersion Tests

	[Fact]
	public Task GetKeyVersionAsync_NonExistentVersion_ShouldReturnNull_Test() =>
		GetKeyVersionAsync_NonExistentVersion_ShouldReturnNull();

	[Fact]
	public Task GetKeyVersionAsync_ExistingVersion_ShouldReturnCorrectMetadata_Test() =>
		GetKeyVersionAsync_ExistingVersion_ShouldReturnCorrectMetadata();

	#endregion GetKeyVersion Tests

	#region ListKeys Tests

	[Fact]
	public Task ListKeysAsync_NoKeys_ShouldReturnEmptyList_Test() =>
		ListKeysAsync_NoKeys_ShouldReturnEmptyList();

	[Fact]
	public Task ListKeysAsync_FilterByStatus_ShouldFilterCorrectly_Test() =>
		ListKeysAsync_FilterByStatus_ShouldFilterCorrectly();

	[Fact]
	public Task ListKeysAsync_FilterByPurpose_ShouldFilterCorrectly_Test() =>
		ListKeysAsync_FilterByPurpose_ShouldFilterCorrectly();

	#endregion ListKeys Tests

	#region RotateKey Tests

	[Fact]
	public Task RotateKeyAsync_NewKey_ShouldCreateVersion1_Test() =>
		RotateKeyAsync_NewKey_ShouldCreateVersion1();

	[Fact]
	public Task RotateKeyAsync_ExistingKey_ShouldCreateNewVersionAndMarkOldDecryptOnly_Test() =>
		RotateKeyAsync_ExistingKey_ShouldCreateNewVersionAndMarkOldDecryptOnly();

	[Fact]
	public Task RotateKeyAsync_NullKeyId_ShouldThrowArgumentException_Test() =>
		RotateKeyAsync_NullKeyId_ShouldThrowArgumentException();

	#endregion RotateKey Tests

	#region DeleteKey Tests

	[Fact]
	public Task DeleteKeyAsync_NonExistent_ShouldReturnFalse_Test() =>
		DeleteKeyAsync_NonExistent_ShouldReturnFalse();

	[Fact]
	public Task DeleteKeyAsync_ExistingKey_ShouldScheduleForDestruction_Test() =>
		DeleteKeyAsync_ExistingKey_ShouldScheduleForDestruction();

	#endregion DeleteKey Tests

	#region SuspendKey Tests

	[Fact]
	public Task SuspendKeyAsync_NonExistent_ShouldReturnFalse_Test() =>
		SuspendKeyAsync_NonExistent_ShouldReturnFalse();

	[Fact]
	public Task SuspendKeyAsync_ExistingKey_ShouldSuspendAllVersions_Test() =>
		SuspendKeyAsync_ExistingKey_ShouldSuspendAllVersions();

	[Fact]
	public Task SuspendKeyAsync_NullReason_ShouldThrowArgumentException_Test() =>
		SuspendKeyAsync_NullReason_ShouldThrowArgumentException();

	#endregion SuspendKey Tests

	#region ReactivateKey Tests

	[Fact]
	public Task ReactivateKeyAsync_NonExistent_ShouldReturnFalse_Test() =>
		ReactivateKeyAsync_NonExistent_ShouldReturnFalse();

	[Fact]
	public Task ReactivateKeyAsync_SuspendedKey_ShouldRestoreToActive_Test() =>
		ReactivateKeyAsync_SuspendedKey_ShouldRestoreToActive();

	#endregion ReactivateKey Tests

	#region GetActiveKey Tests

	[Fact]
	public Task GetActiveKeyAsync_NoActiveKey_ShouldReturnNull_Test() =>
		GetActiveKeyAsync_NoActiveKey_ShouldReturnNull();

	[Fact]
	public Task GetActiveKeyAsync_ActiveKeyExists_ShouldReturnActiveKey_Test() =>
		GetActiveKeyAsync_ActiveKeyExists_ShouldReturnActiveKey();

	[Fact]
	public Task GetActiveKeyAsync_FilterByPurpose_ShouldFilterCorrectly_Test() =>
		GetActiveKeyAsync_FilterByPurpose_ShouldFilterCorrectly();

	[Fact]
	public Task GetActiveKeyAsync_SuspendedKey_ShouldNotReturn_Test() =>
		GetActiveKeyAsync_SuspendedKey_ShouldNotReturn();

	#endregion GetActiveKey Tests

	#region Disposable Tests

	[Fact]
	public Task Disposed_Provider_ShouldThrowObjectDisposedException_Test() =>
		Disposed_Provider_ShouldThrowObjectDisposedException();

	#endregion Disposable Tests
}
