//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excalibur.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excalibur.Security.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashLength must be at least 16 bytes..
        /// </summary>
        internal static string Argon2HashLengthMinimum {
            get {
                return ResourceManager.GetString("Argon2HashLengthMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations must be at least 1..
        /// </summary>
        internal static string Argon2IterationsMinimum {
            get {
                return ResourceManager.GetString("Argon2IterationsMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemorySize must be at least 8192 KB (8 MB)..
        /// </summary>
        internal static string Argon2MemorySizeMinimum {
            get {
                return ResourceManager.GetString("Argon2MemorySizeMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options value cannot be null..
        /// </summary>
        internal static string Argon2OptionsValueNull {
            get {
                return ResourceManager.GetString("Argon2OptionsValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallelism must be at least 1..
        /// </summary>
        internal static string Argon2ParallelismMinimum {
            get {
                return ResourceManager.GetString("Argon2ParallelismMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty or whitespace..
        /// </summary>
        internal static string Argon2PasswordEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Argon2PasswordEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaltLength must be at least 16 bytes..
        /// </summary>
        internal static string Argon2SaltLengthMinimum {
            get {
                return ResourceManager.GetString("Argon2SaltLengthMinimum", resourceCulture);
            }
        }
    }
}
