using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Excalibur.Dispatch.Compat.MediatR.SourceGenerators;

/// <summary>
/// Incremental source generator for the MediatR compatibility surface.
/// Discovers consumer implementations of the compat handler interfaces at compile time and (in later
/// stages) emits canonical <c>IDispatchAction</c> wrapper types, adapter handlers, the runtime
/// request→bridge registry, and an <c>AddMediatRCompatGenerated</c> registration method — all AOT-safe,
/// with no runtime reflection. The canonical <c>Excalibur.Dispatch.SourceGenerators</c> never sees these
/// types (same-pass generators do not observe each other's output), so this generator is self-contained.
/// </summary>
[Generator]
public sealed class MediatRCompatSourceGenerator : IIncrementalGenerator
{
    private const string CompatNamespace = "Excalibur.Dispatch.Compat.MediatR";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is TypeDeclarationSyntax { BaseList: not null } decl
                    && !decl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.AbstractKeyword)),
                transform: static (ctx, ct) => GetHandlerInfo(ctx, ct))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        context.RegisterSourceOutput(handlers.Collect(), static (spc, items) => Emit(spc, items));
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx, CancellationToken cancellationToken)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol((TypeDeclarationSyntax)ctx.Node, cancellationToken)
            is not INamedTypeSymbol symbol || symbol.IsAbstract)
        {
            return null;
        }

        // Open-generic handlers (e.g. Handler<T> : IRequestHandler<Req<T>, T>) cannot be bound to a closed
        // bridge without reflection (AOT-hostile). They are a documented manual-migration step (spec OS-1),
        // so they are skipped here rather than emitting an unbound type parameter.
        if (symbol.IsGenericType || symbol.IsUnboundGenericType)
        {
            return null;
        }

        foreach (var iface in symbol.AllInterfaces)
        {
            if (iface.ContainingNamespace?.ToDisplayString() != CompatNamespace)
            {
                continue;
            }

            // Skip if the interface still carries an unbound type parameter (defensive).
            if (iface.TypeArguments.Any(static t => t.TypeKind == TypeKind.TypeParameter))
            {
                continue;
            }

            var implType = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var args = iface.TypeArguments;

            switch (iface.Name)
            {
                case "IRequestHandler" when args.Length == 2:
                    return new HandlerInfo(
                        HandlerKind.Request,
                        implType,
                        args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                case "INotificationHandler" when args.Length == 1:
                    return new HandlerInfo(
                        HandlerKind.Notification,
                        implType,
                        args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        ResponseType: string.Empty);
                case "IStreamRequestHandler" when args.Length == 2:
                    return new HandlerInfo(
                        HandlerKind.Stream,
                        implType,
                        args[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        args[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                default:
                    break;
            }
        }

        return null;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<HandlerInfo> handlers)
    {
        // ADR-341 §9: emit a [ModuleInitializer] that registers each discovered compat handler's bridge +
        // handler-type via the public CompatRegistration API. AddMediatRCompat then filters these by the
        // consumer's registered assemblies. Swap-only, AOT-safe (closed generics, no reflection).
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/> Excalibur.Dispatch.Compat.MediatR source generator (ADR-341 §9).");
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("namespace Excalibur.Dispatch.Compat.MediatR.Generated");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    internal static class MediatRCompatModuleInitializer");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        _ = sb.AppendLine("        internal static void Initialize()");
        _ = sb.AppendLine("        {");

        foreach (var handler in handlers.OrderBy(h => h.ImplementationTypeName, System.StringComparer.Ordinal))
        {
            const string reg = "            global::Excalibur.Dispatch.Compat.MediatR.Routing.CompatRegistration";
            switch (handler.Kind)
            {
                case HandlerKind.Request:
                    _ = sb.AppendLine($"{reg}.RegisterRequest<{handler.RequestType}, {handler.ResponseType}>(typeof({handler.ImplementationTypeName}));");
                    break;
                case HandlerKind.Notification:
                    _ = sb.AppendLine($"{reg}.RegisterNotification<{handler.RequestType}>(typeof({handler.ImplementationTypeName}));");
                    break;
                case HandlerKind.Stream:
                    _ = sb.AppendLine($"{reg}.RegisterStream<{handler.RequestType}, {handler.ResponseType}>(typeof({handler.ImplementationTypeName}));");
                    break;
                default:
                    break;
            }
        }

        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        context.AddSource("MediatRCompatModuleInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private enum HandlerKind
    {
        Request,
        Notification,
        Stream,
    }

    private readonly record struct HandlerInfo(
        HandlerKind Kind,
        string ImplementationTypeName,
        string RequestType,
        string ResponseType);
}
