<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Excalibur.Inbox.Oracle.Tests</RootNamespace>
    <AssemblyName>Excalibur.Inbox.Oracle.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="Testcontainers.Oracle" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Excalibur\Excalibur.Inbox.Oracle\Excalibur.Inbox.Oracle.csproj" />
    <ProjectReference Include="..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>
</Project>
