//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excalibur.Dispatch.AuditLogging.Splunk {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excalibur.Dispatch.AuditLogging.Splunk.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error exporting batch chunk to Splunk.
        /// </summary>
        internal static string SplunkAuditExporter_ExportBatchChunkError {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_ExportBatchChunkError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exported batch of {TotalCount} audit events to Splunk. Success: {SuccessCount}, Failed: {FailedCount}.
        /// </summary>
        internal static string SplunkAuditExporter_ExportBatchSummary {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_ExportBatchSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exported audit event {EventId} to Splunk.
        /// </summary>
        internal static string SplunkAuditExporter_ExportedAuditEvent {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_ExportedAuditEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export audit event {EventId} to Splunk. Status: {StatusCode}, Response: {Response}.
        /// </summary>
        internal static string SplunkAuditExporter_ExportFailedStatus {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_ExportFailedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed after all retry attempts.
        /// </summary>
        internal static string SplunkAuditExporter_FailedAfterRetries {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_FailedAfterRetries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Splunk HEC health check failed.
        /// </summary>
        internal static string SplunkAuditExporter_HealthCheckFailed {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_HealthCheckFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HTTP error exporting audit event {EventId} to Splunk.
        /// </summary>
        internal static string SplunkAuditExporter_HttpErrorExportingEvent {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_HttpErrorExportingEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request timed out.
        /// </summary>
        internal static string SplunkAuditExporter_RequestTimedOut {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_RequestTimedOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retrying Splunk export (attempt {Attempt}) after {Delay}ms due to {StatusCode}.
        /// </summary>
        internal static string SplunkAuditExporter_RetryingExport {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_RetryingExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeout exporting audit event {EventId} to Splunk.
        /// </summary>
        internal static string SplunkAuditExporter_TimeoutExportingEvent {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_TimeoutExportingEvent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string SplunkAuditExporter_UnknownError {
            get {
                return ResourceManager.GetString("SplunkAuditExporter_UnknownError", resourceCulture);
            }
        }
    }
}
