using System.Globalization;

using Excalibur.Dispatch.Compliance;

using Microsoft.Extensions.Logging.Abstractions;

namespace Excalibur.Dispatch.Compliance.Tests.Audit;

[Trait("Category", "Unit")]
[Trait("Component", "Compliance")]
public sealed class AuditLogEncryptionServiceShould : IDisposable
{
	private readonly IEncryptionProvider _encryptionProvider = A.Fake<IEncryptionProvider>();
	private readonly IKeyManagementProvider _keyManagementProvider = A.Fake<IKeyManagementProvider>();
	private readonly AuditLogEncryptionOptions _options = new()
	{
		EncryptFields = ["ActorId", "IpAddress"],
		KeyIdentifier = "test-audit-key"
	};

	private readonly NullLogger<AuditLogEncryptionService> _logger = NullLogger<AuditLogEncryptionService>.Instance;

	// Real provider pair for round-trip tests (Sprint 686 T.2 regression)
	private readonly InMemoryKeyManagementProvider _realKeyManagement;
	private readonly AesGcmEncryptionProvider _realEncryptionProvider;

	public AuditLogEncryptionServiceShould()
	{
		_realKeyManagement = new InMemoryKeyManagementProvider(
			NullLogger<InMemoryKeyManagementProvider>.Instance,
			new InMemoryKeyManagementOptions
			{
				AutoGenerateDefaultKey = true,
				DefaultKeyId = "test-audit-key"
			});
		_realEncryptionProvider = new AesGcmEncryptionProvider(
			_realKeyManagement,
			NullLogger<AesGcmEncryptionProvider>.Instance);
	}

	[Fact]
	public async Task Encrypt_specified_fields()
	{
		A.CallTo(() => _encryptionProvider.EncryptAsync(A<byte[]>._, A<EncryptionContext>._, A<CancellationToken>._))
			.Returns(new EncryptedData
			{
				Ciphertext = [1, 2, 3],
				KeyId = "test-audit-key",
				KeyVersion = 1,
				Algorithm = EncryptionAlgorithm.Aes256Gcm,
				Iv = new byte[12],
				AuthTag = new byte[16]
			});

		var sut = CreateService();
		var entry = CreateAuditEvent();

		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		encrypted.ShouldNotBeNull();
		encrypted.EventId.ShouldBe(entry.EventId);
		encrypted.KeyIdentifier.ShouldBe("test-audit-key");
		encrypted.EncryptedFields.ShouldContainKey("ActorId");
		encrypted.EncryptedFields.ShouldContainKey("IpAddress");
		encrypted.ClearFields.ShouldNotContainKey("ActorId");
	}

	[Fact]
	public async Task Place_unencrypted_fields_in_clear()
	{
		A.CallTo(() => _encryptionProvider.EncryptAsync(A<byte[]>._, A<EncryptionContext>._, A<CancellationToken>._))
			.Returns(new EncryptedData
			{
				Ciphertext = [1, 2, 3],
				KeyId = "test-audit-key",
				KeyVersion = 1,
				Algorithm = EncryptionAlgorithm.Aes256Gcm,
				Iv = new byte[12],
				AuthTag = new byte[16]
			});

		var sut = CreateService();
		var entry = CreateAuditEvent();

		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		encrypted.ClearFields.ShouldContainKey("Action");
		encrypted.ClearFields.ShouldContainKey("ResourceType");
	}

	[Fact]
	public async Task Throw_for_null_entry_on_encrypt()
	{
		var sut = CreateService();

		await Should.ThrowAsync<ArgumentNullException>(
			() => sut.EncryptAsync(null!, CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public async Task Throw_for_null_entry_on_decrypt()
	{
		var sut = CreateService();

		await Should.ThrowAsync<ArgumentNullException>(
			() => sut.DecryptAsync(null!, CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public async Task Decrypt_encrypted_entry()
	{
		var plaintext = System.Text.Encoding.UTF8.GetBytes("test-actor");
		A.CallTo(() => _encryptionProvider.DecryptAsync(A<EncryptedData>._, A<EncryptionContext>._, A<CancellationToken>._))
			.Returns(plaintext);

		var sut = CreateService();

		// Build a valid envelope: [IV:12][Ciphertext:N][AuthTag:16]
		var iv = new byte[12];
		var ciphertext = new byte[] { 1, 2, 3 };
		var authTag = new byte[16];
		var envelope = new byte[iv.Length + ciphertext.Length + authTag.Length];
		iv.CopyTo(envelope, 0);
		ciphertext.CopyTo(envelope, iv.Length);
		authTag.CopyTo(envelope, iv.Length + ciphertext.Length);

		var encryptedEntry = new EncryptedAuditEntry
		{
			EventId = "evt-1",
			EncryptedFields = new Dictionary<string, byte[]>
			{
				["ActorId"] = envelope
			},
			ClearFields = new Dictionary<string, string>
			{
				["Action"] = "Login",
				["EventType"] = "System",
				["Outcome"] = "Success",
				["Timestamp"] = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture)
			},
			KeyIdentifier = "test-audit-key",
			Algorithm = EncryptionAlgorithm.Aes256Gcm
		};

		var decrypted = await sut.DecryptAsync(encryptedEntry, CancellationToken.None).ConfigureAwait(false);

		decrypted.ShouldNotBeNull();
		decrypted.EventId.ShouldBe("evt-1");
		decrypted.ActorId.ShouldBe("test-actor");
		decrypted.Action.ShouldBe("Login");
	}

	// =====================================================================
	// Sprint 686 T.2 (7o2is) -- AES-GCM round-trip regression tests
	// These use REAL AesGcmEncryptionProvider + InMemoryKeyManagementProvider
	// to ensure the envelope format [IV:12][CT:N][AuthTag:16] works end-to-end.
	// =====================================================================

	[Fact]
	public async Task RoundTrip_EncryptDecrypt_WithRealProvider()
	{
		// Arrange
		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);
		var decrypted = await sut.DecryptAsync(encrypted, CancellationToken.None).ConfigureAwait(false);

		// Assert
		decrypted.ShouldNotBeNull();
		decrypted.ActorId.ShouldBe(entry.ActorId);
		decrypted.IpAddress.ShouldBe(entry.IpAddress);
		decrypted.Action.ShouldBe(entry.Action);
		decrypted.EventType.ShouldBe(entry.EventType);
		decrypted.Outcome.ShouldBe(entry.Outcome);
		decrypted.ResourceId.ShouldBe(entry.ResourceId);
		decrypted.ResourceType.ShouldBe(entry.ResourceType);
	}

	[Fact]
	public async Task RoundTrip_MultipleFields_WithRealProvider()
	{
		// Arrange -- encrypt 3+ fields
		var options = new AuditLogEncryptionOptions
		{
			EncryptFields = ["ActorId", "IpAddress", "Reason"],
			KeyIdentifier = "test-audit-key"
		};
		var sut = new AuditLogEncryptionService(
			_realEncryptionProvider,
			_realKeyManagement,
			Microsoft.Extensions.Options.Options.Create(options),
			_logger);

		var entry = CreateAuditEventWithReason("Suspicious login from new device");

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);
		var decrypted = await sut.DecryptAsync(encrypted, CancellationToken.None).ConfigureAwait(false);

		// Assert
		encrypted.EncryptedFields.Count.ShouldBe(3);
		encrypted.EncryptedFields.ShouldContainKey("ActorId");
		encrypted.EncryptedFields.ShouldContainKey("IpAddress");
		encrypted.EncryptedFields.ShouldContainKey("Reason");

		decrypted.ActorId.ShouldBe("user-123");
		decrypted.IpAddress.ShouldBe("192.168.1.1");
		decrypted.Reason.ShouldBe("Suspicious login from new device");
	}

	[Fact]
	public async Task Envelope_HasCorrectSize_WithRealProvider()
	{
		// Arrange
		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		// Assert -- envelope = IV(12) + ciphertext(N) + AuthTag(16)
		// For each encrypted field, verify envelope is at least MinEnvelopeSize (28) bytes
		foreach (var (fieldName, envelope) in encrypted.EncryptedFields)
		{
			envelope.Length.ShouldBeGreaterThanOrEqualTo(28,
				$"Envelope for '{fieldName}' should be at least 28 bytes (12 IV + 0 CT min + 16 AuthTag)");

			// The original plaintext is the field value encoded as UTF-8
			// envelope.Length should be 12 + plaintextBytes.Length + 16
			var expectedLength = 12 + System.Text.Encoding.UTF8.GetByteCount(
				fieldName == "ActorId" ? entry.ActorId : entry.IpAddress!) + 16;
			envelope.Length.ShouldBe(expectedLength,
				$"Envelope for '{fieldName}' size mismatch");
		}
	}

	[Fact]
	public async Task Decrypt_RejectsShortCiphertext()
	{
		// Arrange -- envelope shorter than MinEnvelopeSize (28 bytes = 12 IV + 16 AuthTag)
		var sut = CreateRealService();
		var encryptedEntry = new EncryptedAuditEntry
		{
			EventId = "evt-short",
			EncryptedFields = new Dictionary<string, byte[]>
			{
				["ActorId"] = new byte[10] // Too short
			},
			ClearFields = new Dictionary<string, string>
			{
				["Action"] = "Login",
				["EventType"] = "System",
				["Outcome"] = "Success",
				["Timestamp"] = DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture)
			},
			KeyIdentifier = "test-audit-key",
			Algorithm = EncryptionAlgorithm.Aes256Gcm
		};

		// Act & Assert
		await Should.ThrowAsync<EncryptionException>(
			() => sut.DecryptAsync(encryptedEntry, CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public async Task ClearFields_NotEncrypted_WithRealProvider()
	{
		// Arrange
		var sut = CreateRealService();
		var entry = CreateAuditEvent();

		// Act
		var encrypted = await sut.EncryptAsync(entry, CancellationToken.None).ConfigureAwait(false);

		// Assert -- fields not in EncryptFields list should remain in ClearFields
		encrypted.ClearFields.ShouldContainKey("Action");
		encrypted.ClearFields["Action"].ShouldBe("Login");
		encrypted.ClearFields.ShouldContainKey("ResourceType");
		encrypted.ClearFields["ResourceType"].ShouldBe("Session");
		encrypted.ClearFields.ShouldNotContainKey("ActorId");
		encrypted.ClearFields.ShouldNotContainKey("IpAddress");
	}

	[Fact]
	public async Task Propagate_encryption_exception()
	{
		A.CallTo(() => _encryptionProvider.EncryptAsync(A<byte[]>._, A<EncryptionContext>._, A<CancellationToken>._))
			.ThrowsAsync(new InvalidOperationException("Key unavailable"));

		var sut = CreateService();

		await Should.ThrowAsync<InvalidOperationException>(
			() => sut.EncryptAsync(CreateAuditEvent(), CancellationToken.None)).ConfigureAwait(false);
	}

	[Fact]
	public void Throw_for_null_encryption_provider()
	{
		Should.Throw<ArgumentNullException>(() =>
			new AuditLogEncryptionService(
				null!,
				_keyManagementProvider,
				Microsoft.Extensions.Options.Options.Create(_options),
				_logger));
	}

	[Fact]
	public void Throw_for_null_key_management_provider()
	{
		Should.Throw<ArgumentNullException>(() =>
			new AuditLogEncryptionService(
				_encryptionProvider,
				null!,
				Microsoft.Extensions.Options.Options.Create(_options),
				_logger));
	}

	[Fact]
	public void Throw_for_null_options()
	{
		Should.Throw<ArgumentNullException>(() =>
			new AuditLogEncryptionService(
				_encryptionProvider,
				_keyManagementProvider,
				null!,
				_logger));
	}

	[Fact]
	public void Throw_for_null_logger()
	{
		Should.Throw<ArgumentNullException>(() =>
			new AuditLogEncryptionService(
				_encryptionProvider,
				_keyManagementProvider,
				Microsoft.Extensions.Options.Options.Create(_options),
				null!));
	}

	public void Dispose()
	{
		_realEncryptionProvider.Dispose();
		_realKeyManagement.Dispose();
	}

	private AuditLogEncryptionService CreateService() =>
		new(
			_encryptionProvider,
			_keyManagementProvider,
			Microsoft.Extensions.Options.Options.Create(_options),
			_logger);

	private AuditLogEncryptionService CreateRealService() =>
		new(
			_realEncryptionProvider,
			_realKeyManagement,
			Microsoft.Extensions.Options.Options.Create(_options),
			_logger);

	private static AuditEvent CreateAuditEvent() =>
		new()
		{
			EventId = "evt-" + Guid.NewGuid().ToString("N")[..8],
			EventType = AuditEventType.Authentication,
			Action = "Login",
			Outcome = AuditOutcome.Success,
			Timestamp = DateTimeOffset.UtcNow,
			ActorId = "user-123",
			ActorType = "User",
			ResourceId = "resource-1",
			ResourceType = "Session",
			IpAddress = "192.168.1.1"
		};

	private static AuditEvent CreateAuditEventWithReason(string reason) =>
		new()
		{
			EventId = "evt-" + Guid.NewGuid().ToString("N")[..8],
			EventType = AuditEventType.Authentication,
			Action = "Login",
			Outcome = AuditOutcome.Success,
			Timestamp = DateTimeOffset.UtcNow,
			ActorId = "user-123",
			ActorType = "User",
			ResourceId = "resource-1",
			ResourceType = "Session",
			IpAddress = "192.168.1.1",
			Reason = reason
		};
}
