// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0


namespace Excalibur.Dispatch.Abstractions;

/// <summary>
/// Implementation of message problem details following RFC 7807.
/// </summary>
public sealed class MessageProblemDetails : IMessageProblemDetails
{
	/// <summary>
	/// Gets or sets a URI reference that identifies the problem type.
	/// </summary>
	/// <value> The problem type URI. </value>
	public string Type { get; set; } = "about:blank";

	/// <summary>
	/// Gets or sets a short, human-readable summary of the problem type.
	/// </summary>
	/// <value> The problem summary. </value>
	public string Title { get; set; } = "Error";

	/// <summary>
	/// Gets or sets the application-specific error code.
	/// </summary>
	/// <value> The application-specific error code. </value>
	public int ErrorCode { get; set; }

	/// <summary>
	/// Gets or sets the HTTP status code generated by the origin server for this occurrence of the problem.
	/// </summary>
	/// <value> The HTTP status code when available. </value>
	public int? Status { get; set; }

	/// <summary>
	/// Gets or sets a human-readable explanation specific to this occurrence of the problem.
	/// </summary>
	/// <value> The problem explanation. </value>
	public string Detail { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets a URI reference that identifies the specific occurrence of the problem.
	/// </summary>
	/// <value> The occurrence URI. </value>
	public string Instance { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets additional members that provide context-specific problem details.
	/// </summary>
	/// <value> A dictionary of additional members. </value>
	public IDictionary<string, object?> Extensions { get; set; } = new Dictionary<string, object?>(StringComparer.Ordinal);

	/// <summary>
	/// Creates problem details for a validation error.
	/// </summary>
	/// <param name="detail"> The error detail. </param>
	/// <returns> Problem details for validation error. </returns>
	public static IMessageProblemDetails ValidationError(string detail) =>
		new MessageProblemDetails { Type = "validation-error", Title = "Validation Error", Detail = detail, Status = 400 };

	/// <summary>
	/// Creates problem details for an authorization error.
	/// </summary>
	/// <param name="detail"> The error detail. </param>
	/// <returns> Problem details for authorization error. </returns>
	public static IMessageProblemDetails AuthorizationError(string detail) =>
		new MessageProblemDetails { Type = "authorization-error", Title = "Authorization Error", Detail = detail, Status = 403 };

	/// <summary>
	/// Creates problem details for a not found error.
	/// </summary>
	/// <param name="detail"> The error detail. </param>
	/// <returns> Problem details for not found error. </returns>
	public static IMessageProblemDetails NotFound(string detail) =>
		new MessageProblemDetails
		{
			Type = "not-found",
			Title = "Not Found",
			Detail = detail,
			Status = 404
		};

	/// <summary>
	/// Creates problem details for an internal error.
	/// </summary>
	/// <param name="detail"> The error detail. </param>
	/// <returns> Problem details for internal error. </returns>
	public static IMessageProblemDetails InternalError(string detail) =>
		new MessageProblemDetails { Type = "internal-error", Title = "Internal Error", Detail = detail, Status = 500 };
}
