// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using CdcAntiCorruption.Models;

using Excalibur.Dispatch.Abstractions;

namespace CdcAntiCorruption.Commands;

/// <summary>
/// Command to synchronize a new customer from a CDC insert event.
/// </summary>
/// <remarks>
/// This command is generated by the anti-corruption layer when a new record
/// is inserted in the legacy customers table. It triggers the creation of
/// a corresponding customer in the domain model.
/// </remarks>
public sealed record SyncCustomerCommand : IDispatchAction<SyncCustomerResult>
{
	/// <summary>
	/// Initializes a new instance of the <see cref="SyncCustomerCommand"/> class.
	/// </summary>
	/// <param name="customerData">The adapted customer data from the CDC event.</param>
	public SyncCustomerCommand(AdaptedCustomerData customerData)
	{
		ArgumentNullException.ThrowIfNull(customerData);
		CustomerData = customerData;
	}

	/// <summary>
	/// Gets the adapted customer data to synchronize.
	/// </summary>
	public AdaptedCustomerData CustomerData { get; }
}

/// <summary>
/// Result of the sync customer command execution.
/// </summary>
public sealed record SyncCustomerResult
{
	/// <summary>
	/// Gets the internal customer ID assigned by the domain.
	/// </summary>
	public required Guid CustomerId { get; init; }

	/// <summary>
	/// Gets a value indicating whether this was a new customer creation.
	/// </summary>
	public bool WasCreated { get; init; }
}
