<?xml version="1.0" encoding="utf-8"?>
<!-- SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project -->
<!-- SPDX-License-Identifier: Apache-2.0 -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Testing</RootNamespace>
  </PropertyGroup>
  <!-- Dispatch packages under test -->
  <ItemGroup>
    <ProjectReference Include="$(DispatchSourceRoot)Excalibur.Dispatch.Abstractions\Excalibur.Dispatch.Abstractions.csproj" />
    <ProjectReference Include="$(DispatchSourceRoot)Excalibur.Dispatch\Excalibur.Dispatch.csproj" />
    <ProjectReference Include="$(DispatchSourceRoot)Excalibur.Dispatch.Testing\Excalibur.Dispatch.Testing.csproj" />
  </ItemGroup>
  <!-- Test framework: xUnit + Shouldly + FakeItEasy -->
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
</Project>
