// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using CdcAntiCorruption.Models;

using Excalibur.Dispatch.Abstractions;

namespace CdcAntiCorruption.Commands;

/// <summary>
/// Command to deactivate a customer from a CDC delete event.
/// </summary>
/// <remarks>
/// <para>
/// This command is generated by the anti-corruption layer when a record
/// is deleted from the legacy customers table. Instead of hard-deleting,
/// this soft-deletes (deactivates) the customer in the domain model.
/// </para>
/// <para>
/// This pattern ensures audit trails are maintained and allows for
/// potential recovery of accidentally deleted records.
/// </para>
/// </remarks>
public sealed record DeactivateCustomerCommand : IDispatchAction<DeactivateCustomerResult>
{
	/// <summary>
	/// Initializes a new instance of the <see cref="DeactivateCustomerCommand"/> class.
	/// </summary>
	/// <param name="customerData">The adapted customer data from the CDC event.</param>
	public DeactivateCustomerCommand(AdaptedCustomerData customerData)
	{
		ArgumentNullException.ThrowIfNull(customerData);
		CustomerData = customerData;
	}

	/// <summary>
	/// Gets the adapted customer data identifying the customer to deactivate.
	/// </summary>
	public AdaptedCustomerData CustomerData { get; }
}

/// <summary>
/// Result of the deactivate customer command execution.
/// </summary>
public sealed record DeactivateCustomerResult
{
	/// <summary>
	/// Gets the internal customer ID that was deactivated.
	/// </summary>
	public required Guid CustomerId { get; init; }

	/// <summary>
	/// Gets a value indicating whether the customer was found and deactivated.
	/// </summary>
	public bool WasDeactivated { get; init; }

	/// <summary>
	/// Gets a value indicating whether the customer was already inactive.
	/// </summary>
	public bool WasAlreadyInactive { get; init; }
}
