// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using CdcAntiCorruption.Models;

using Excalibur.Dispatch.Abstractions;

namespace CdcAntiCorruption.Commands;

/// <summary>
/// Command to update an existing customer from a CDC update event.
/// </summary>
/// <remarks>
/// This command is generated by the anti-corruption layer when an existing record
/// is updated in the legacy customers table. It applies the changes to the
/// corresponding customer in the domain model.
/// </remarks>
public sealed record UpdateCustomerCommand : IDispatchAction<UpdateCustomerResult>
{
	/// <summary>
	/// Initializes a new instance of the <see cref="UpdateCustomerCommand"/> class.
	/// </summary>
	/// <param name="customerData">The adapted customer data from the CDC event.</param>
	public UpdateCustomerCommand(AdaptedCustomerData customerData)
	{
		ArgumentNullException.ThrowIfNull(customerData);
		CustomerData = customerData;
	}

	/// <summary>
	/// Gets the adapted customer data with updated values.
	/// </summary>
	public AdaptedCustomerData CustomerData { get; }
}

/// <summary>
/// Result of the update customer command execution.
/// </summary>
public sealed record UpdateCustomerResult
{
	/// <summary>
	/// Gets the internal customer ID that was updated.
	/// </summary>
	public required Guid CustomerId { get; init; }

	/// <summary>
	/// Gets a value indicating whether the customer was found and updated.
	/// </summary>
	public bool WasUpdated { get; init; }

	/// <summary>
	/// Gets a value indicating whether the customer was not found (and possibly created).
	/// </summary>
	public bool WasNotFound { get; init; }
}
