// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using Excalibur.Dispatch.Compliance;
using Excalibur.Dispatch.Security;

using Excalibur.Testing.Conformance;

using Microsoft.Extensions.Logging.Abstractions;

using Xunit;

namespace Excalibur.Tests.Testing.Conformance;

/// <summary>
/// Conformance tests for <see cref="EncryptionMigrationService"/> validating IEncryptionMigrationService contract compliance.
/// </summary>
/// <remarks>
/// <para>
/// EncryptionMigrationService provides RE-ENCRYPTION capabilities for migrating encrypted data
/// between providers, algorithms, or key versions.
/// </para>
/// <para>
/// <strong>COMPLIANCE-CRITICAL:</strong> IEncryptionMigrationService implements GDPR crypto-shredding
/// support by enabling re-encryption with new keys before destroying old keys.
/// </para>
/// <para>
/// Key behaviors verified:
/// <list type="bullet">
/// <item><description>MigrateAsync null throws ArgumentNullException (x3)</description></item>
/// <item><description>MigrateAsync valid data returns successful result</description></item>
/// <item><description>MigrateAsync round-trip preserves original plaintext</description></item>
/// <item><description>MigrateBatchAsync null throws ArgumentNullException (x3)</description></item>
/// <item><description>MigrateBatchAsync valid batch returns successful result</description></item>
/// <item><description>MigrateBatchAsync empty batch returns successful result</description></item>
/// <item><description>RequiresMigrationAsync null throws ArgumentNullException (x2)</description></item>
/// <item><description>RequiresMigrationAsync deprecated key returns true</description></item>
/// <item><description>RequiresMigrationAsync no match returns false</description></item>
/// <item><description>GetMigrationStatusAsync null throws ArgumentNullException</description></item>
/// <item><description>GetMigrationStatusAsync non-existent returns null</description></item>
/// <item><description>GetMigrationStatusAsync after migration returns status</description></item>
/// <item><description>EstimateMigrationAsync null throws ArgumentNullException</description></item>
/// <item><description>EstimateMigrationAsync valid policy returns estimate</description></item>
/// </list>
/// </para>
/// </remarks>
[System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test method naming convention")]
[Trait("Category", "Integration")]
[Trait("Component", "Compliance")]
[Trait("Pattern", "SERVICE")]
public sealed class EncryptionMigrationServiceConformanceTests : EncryptionMigrationServiceConformanceTestKit, IDisposable
{
	private InMemoryKeyManagementProvider? _keyManagementProvider;
	private AesGcmEncryptionProvider? _encryptionProvider;

	/// <inheritdoc />
	public void Dispose()
	{
		_encryptionProvider?.Dispose();
		_keyManagementProvider?.Dispose();
	}

	/// <inheritdoc />
	protected override Task<(IEncryptionMigrationService Service, IEncryptionProvider Encryption, IKeyManagementProvider KeyManagement)> CreateServiceAsync()
	{
		// Create key management provider with auto-generated default key
		_keyManagementProvider = new InMemoryKeyManagementProvider(
			NullLogger<InMemoryKeyManagementProvider>.Instance,
			new InMemoryKeyManagementOptions { AutoGenerateDefaultKey = true });

		// Create AES-GCM encryption provider
		_encryptionProvider = new AesGcmEncryptionProvider(
			_keyManagementProvider,
			NullLogger<AesGcmEncryptionProvider>.Instance);

		// Create the migration service
		var service = new EncryptionMigrationService(
			_encryptionProvider,
			NullLogger<EncryptionMigrationService>.Instance);

		return Task.FromResult<(IEncryptionMigrationService, IEncryptionProvider, IKeyManagementProvider)>(
			(service, _encryptionProvider, _keyManagementProvider));
	}

	#region MigrateAsync Tests

	[Fact]
	public Task MigrateAsync_NullEncryptedData_ShouldThrowArgumentNullException_Test() =>
		MigrateAsync_NullEncryptedData_ShouldThrowArgumentNullException();

	[Fact]
	public Task MigrateAsync_NullSourceContext_ShouldThrowArgumentNullException_Test() =>
		MigrateAsync_NullSourceContext_ShouldThrowArgumentNullException();

	[Fact]
	public Task MigrateAsync_NullTargetContext_ShouldThrowArgumentNullException_Test() =>
		MigrateAsync_NullTargetContext_ShouldThrowArgumentNullException();

	[Fact]
	public Task MigrateAsync_ValidData_ShouldReturnSuccessfulResult_Test() =>
		MigrateAsync_ValidData_ShouldReturnSuccessfulResult();

	[Fact]
	public Task MigrateAsync_RoundTrip_ShouldPreserveOriginalPlaintext_Test() =>
		MigrateAsync_RoundTrip_ShouldPreserveOriginalPlaintext();

	#endregion MigrateAsync Tests

	#region MigrateBatchAsync Tests

	[Fact]
	public Task MigrateBatchAsync_NullItems_ShouldThrowArgumentNullException_Test() =>
		MigrateBatchAsync_NullItems_ShouldThrowArgumentNullException();

	[Fact]
	public Task MigrateBatchAsync_NullTargetContext_ShouldThrowArgumentNullException_Test() =>
		MigrateBatchAsync_NullTargetContext_ShouldThrowArgumentNullException();

	[Fact]
	public Task MigrateBatchAsync_NullOptions_ShouldThrowArgumentNullException_Test() =>
		MigrateBatchAsync_NullOptions_ShouldThrowArgumentNullException();

	[Fact]
	public Task MigrateBatchAsync_ValidBatch_ShouldReturnSuccessfulResult_Test() =>
		MigrateBatchAsync_ValidBatch_ShouldReturnSuccessfulResult();

	[Fact]
	public Task MigrateBatchAsync_EmptyBatch_ShouldReturnSuccessfulResult_Test() =>
		MigrateBatchAsync_EmptyBatch_ShouldReturnSuccessfulResult();

	#endregion MigrateBatchAsync Tests

	#region RequiresMigrationAsync Tests

	[Fact]
	public Task RequiresMigrationAsync_NullEncryptedData_ShouldThrowArgumentNullException_Test() =>
		RequiresMigrationAsync_NullEncryptedData_ShouldThrowArgumentNullException();

	[Fact]
	public Task RequiresMigrationAsync_NullPolicy_ShouldThrowArgumentNullException_Test() =>
		RequiresMigrationAsync_NullPolicy_ShouldThrowArgumentNullException();

	[Fact]
	public Task RequiresMigrationAsync_DeprecatedKeyId_ShouldReturnTrue_Test() =>
		RequiresMigrationAsync_DeprecatedKeyId_ShouldReturnTrue();

	[Fact]
	public Task RequiresMigrationAsync_NoMatchingPolicy_ShouldReturnFalse_Test() =>
		RequiresMigrationAsync_NoMatchingPolicy_ShouldReturnFalse();

	#endregion RequiresMigrationAsync Tests

	#region GetMigrationStatusAsync Tests

	[Fact]
	public Task GetMigrationStatusAsync_NullMigrationId_ShouldThrowArgumentNullException_Test() =>
		GetMigrationStatusAsync_NullMigrationId_ShouldThrowArgumentNullException();

	[Fact]
	public Task GetMigrationStatusAsync_NonExistentMigration_ShouldReturnNull_Test() =>
		GetMigrationStatusAsync_NonExistentMigration_ShouldReturnNull();

	[Fact]
	public Task GetMigrationStatusAsync_AfterBatchMigration_ShouldReturnStatus_Test() =>
		GetMigrationStatusAsync_AfterBatchMigration_ShouldReturnStatus();

	#endregion GetMigrationStatusAsync Tests

	#region EstimateMigrationAsync Tests

	[Fact]
	public Task EstimateMigrationAsync_NullPolicy_ShouldThrowArgumentNullException_Test() =>
		EstimateMigrationAsync_NullPolicy_ShouldThrowArgumentNullException();

	[Fact]
	public Task EstimateMigrationAsync_ValidPolicy_ShouldReturnEstimate_Test() =>
		EstimateMigrationAsync_ValidPolicy_ShouldReturnEstimate();

	#endregion EstimateMigrationAsync Tests
}
