// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using Excalibur.Compliance;
using Excalibur.Compliance.Encryption;
using Excalibur.Compliance.KeyManagement;

using Excalibur.Testing.Conformance;

using Microsoft.Extensions.Logging.Abstractions;

using Xunit;

namespace Excalibur.Tests.Testing.Conformance;

/// <summary>
/// Conformance tests for <see cref="KeyEscrowBackupService"/> validating IKeyEscrowService contract compliance.
/// </summary>
/// <remarks>
/// <para>
/// KeyEscrowBackupService is the in-memory implementation of key escrow: encrypted key backup gated by a
/// fail-closed Shamir M-of-N recovery-authorization quorum.
/// </para>
/// <para>
/// <strong>KEY PATTERN:</strong> ESCROW-RECOVERY - Backup -> Generate Tokens -> Recover -> Revoke.
/// </para>
/// </remarks>
[System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Test method naming convention")]
[Trait("Category", "Integration")]
[Trait("Component", "Compliance")]
[Trait("Pattern", "SERVICE")]
public sealed class InMemoryKeyEscrowServiceConformanceTests : KeyEscrowServiceConformanceTestKit, IDisposable
{
	private InMemoryKeyManagementProvider? _keyManagementProvider;
	private AesGcmEncryptionProvider? _encryptionProvider;

	/// <inheritdoc />
	public void Dispose()
	{
		_encryptionProvider?.Dispose();
		_keyManagementProvider?.Dispose();
	}

	/// <inheritdoc />
	protected override IKeyEscrowService CreateService()
	{
		_keyManagementProvider = new InMemoryKeyManagementProvider(
			NullLogger<InMemoryKeyManagementProvider>.Instance,
			new InMemoryKeyManagementOptions
			{
				AutoGenerateDefaultKey = true,

				// KeyEscrowBackupService encrypts every escrowed key under the logical master-key selector
				// "escrow-master-key". The auto-generated key must carry that id or encryption finds no key.
				DefaultKeyId = "escrow-master-key",
			});

		_encryptionProvider = new AesGcmEncryptionProvider(
			_keyManagementProvider,
			NullLogger<AesGcmEncryptionProvider>.Instance);

		return new KeyEscrowBackupService(
			_encryptionProvider,
			NullLogger<KeyEscrowBackupService>.Instance);
	}

	#region BackupKeyAsync Tests

	[Fact]
	public Task BackupKeyAsync_NullKeyId_ShouldThrowArgumentException_Test() =>
		BackupKeyAsync_NullKeyId_ShouldThrowArgumentException();

	[Fact]
	public Task BackupKeyAsync_EmptyKeyMaterial_ShouldThrowArgumentException_Test() =>
		BackupKeyAsync_EmptyKeyMaterial_ShouldThrowArgumentException();

	[Fact]
	public Task BackupKeyAsync_ValidKeyMaterial_ShouldReturnReceipt_Test() =>
		BackupKeyAsync_ValidKeyMaterial_ShouldReturnReceipt();

	[Fact]
	public Task BackupKeyAsync_DuplicateKey_ShouldThrowKeyEscrowException_Test() =>
		BackupKeyAsync_DuplicateKey_ShouldThrowKeyEscrowException();

	#endregion BackupKeyAsync Tests

	#region RecoverKeyAsync Tests

	[Fact]
	public Task RecoverKeyAsync_NullKeyId_ShouldThrowArgumentException_Test() =>
		RecoverKeyAsync_NullKeyId_ShouldThrowArgumentException();

	[Fact]
	public Task RecoverKeyAsync_NonExistentKey_ShouldThrowKeyEscrowException_Test() =>
		RecoverKeyAsync_NonExistentKey_ShouldThrowKeyEscrowException();

	[Fact]
	public Task RecoverKeyAsync_ValidToken_ShouldReturnKeyMaterial_Test() =>
		RecoverKeyAsync_ValidToken_ShouldReturnKeyMaterial();

	[Fact]
	public Task RecoverKeyAsync_SingleShareBelowThreshold_ShouldFailClosed_Test() =>
		RecoverKeyAsync_SingleShareBelowThreshold_ShouldFailClosed();

	[Fact]
	public Task RecoverKeyAsync_RevokedEscrow_ShouldThrowKeyEscrowException_Test() =>
		RecoverKeyAsync_RevokedEscrow_ShouldThrowKeyEscrowException();

	#endregion RecoverKeyAsync Tests

	#region GenerateRecoveryTokensAsync Tests

	[Fact]
	public Task GenerateRecoveryTokensAsync_NullKeyId_ShouldThrowArgumentException_Test() =>
		GenerateRecoveryTokensAsync_NullKeyId_ShouldThrowArgumentException();

	[Fact]
	public Task GenerateRecoveryTokensAsync_ThresholdLessThan2_ShouldThrowArgumentOutOfRangeException_Test() =>
		GenerateRecoveryTokensAsync_ThresholdLessThan2_ShouldThrowArgumentOutOfRangeException();

	[Fact]
	public Task GenerateRecoveryTokensAsync_ValidParams_ShouldGenerateCorrectCount_Test() =>
		GenerateRecoveryTokensAsync_ValidParams_ShouldGenerateCorrectCount();

	#endregion GenerateRecoveryTokensAsync Tests

	#region RevokeEscrowAsync Tests

	[Fact]
	public Task RevokeEscrowAsync_NullKeyId_ShouldThrowArgumentException_Test() =>
		RevokeEscrowAsync_NullKeyId_ShouldThrowArgumentException();

	[Fact]
	public Task RevokeEscrowAsync_NonExistentKey_ShouldReturnFalse_Test() =>
		RevokeEscrowAsync_NonExistentKey_ShouldReturnFalse();

	[Fact]
	public Task RevokeEscrowAsync_ExistingEscrow_ShouldReturnTrue_Test() =>
		RevokeEscrowAsync_ExistingEscrow_ShouldReturnTrue();

	#endregion RevokeEscrowAsync Tests

	#region GetEscrowStatusAsync Tests

	[Fact]
	public Task GetEscrowStatusAsync_NullKeyId_ShouldThrowArgumentException_Test() =>
		GetEscrowStatusAsync_NullKeyId_ShouldThrowArgumentException();

	[Fact]
	public Task GetEscrowStatusAsync_NonExistentKey_ShouldReturnNull_Test() =>
		GetEscrowStatusAsync_NonExistentKey_ShouldReturnNull();

	[Fact]
	public Task GetEscrowStatusAsync_ExistingEscrow_ShouldReturnStatus_Test() =>
		GetEscrowStatusAsync_ExistingEscrow_ShouldReturnStatus();

	#endregion GetEscrowStatusAsync Tests

	#region Suite Wiring

	/// <summary>
	/// Fails if this suite stops exposing any arm the kit declares.
	/// </summary>
	/// <remarks>
	/// An arm nobody wires never executes, and an arm that never executes cannot fail - in the results it
	/// is indistinguishable from one that passed. That is why the wiring is checked rather than trusted to
	/// survive an edit: a new arm added to the shipped kit turns this red here instead of going silently
	/// unrun.
	/// </remarks>
	[Fact]
	public Task ConformanceSuite_ShouldWireEveryArm_Test() => ConformanceSuite_ShouldWireEveryArm();

	#endregion
}
