//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excalibur.Dispatch.Compliance {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excalibur.Dispatch.Compliance.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error detecting FIPS compliance status.
        /// </summary>
        internal static string DefaultFipsDetector_ErrorDetectingStatus {
            get {
                return ResourceManager.GetString("DefaultFipsDetector_ErrorDetectingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error reading Linux FIPS status.
        /// </summary>
        internal static string DefaultFipsDetector_ErrorReadingLinuxStatus {
            get {
                return ResourceManager.GetString("DefaultFipsDetector_ErrorReadingLinuxStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Linux FIPS mode: {IsFipsEnabled} (value: {Value}).
        /// </summary>
        internal static string DefaultFipsDetector_LinuxFipsMode {
            get {
                return ResourceManager.GetString("DefaultFipsDetector_LinuxFipsMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Windows FIPS mode: {IsFipsEnabled}.
        /// </summary>
        internal static string DefaultFipsDetector_WindowsFipsMode {
            get {
                return ResourceManager.GetString("DefaultFipsDetector_WindowsFipsMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DEV ENCRYPTION IS ACTIVE. In-memory key management is being used. Keys are not persisted and will be lost on restart. Do NOT use this configuration in production. Configure a production key management provider using AddEncryption()..
        /// </summary>
        internal static string DevEncryptionWarningLogger_Message {
            get {
                return ResourceManager.GetString("DevEncryptionWarningLogger_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No encryption providers were registered. Call UseInMemoryKeyManagement(), UseKeyManagement&lt;T&gt;(), or UseProvider() to register at least one provider..
        /// </summary>
        internal static string EncryptionConfigurationBuilder_NoProvidersRegistered {
            get {
                return ResourceManager.GetString("EncryptionConfigurationBuilder_NoProvidersRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider '{0}' was not registered in this builder. Register the provider first..
        /// </summary>
        internal static string EncryptionConfigurationBuilder_ProviderNotRegistered {
            get {
                return ResourceManager.GetString("EncryptionConfigurationBuilder_ProviderNotRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary region configuration is required..
        /// </summary>
        internal static string ComplianceServiceCollectionExtensions_PrimaryRegionConfigurationRequired {
            get {
                return ResourceManager.GetString("ComplianceServiceCollectionExtensions_PrimaryRegionConfigurationRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secondary region configuration is required..
        /// </summary>
        internal static string ComplianceServiceCollectionExtensions_SecondaryRegionConfigurationRequired {
            get {
                return ResourceManager.GetString("ComplianceServiceCollectionExtensions_SecondaryRegionConfigurationRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Outbox store is in read-only mode. Writes are not permitted during this encryption migration phase..
        /// </summary>
        internal static string EncryptingOutboxStoreDecorator_ReadOnlyMode {
            get {
                return ResourceManager.GetString("EncryptingOutboxStoreDecorator_ReadOnlyMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inbox store is in read-only mode. Writes are not permitted during this encryption migration phase..
        /// </summary>
        internal static string EncryptingInboxStoreDecorator_ReadOnlyMode {
            get {
                return ResourceManager.GetString("EncryptingInboxStoreDecorator_ReadOnlyMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created evidence package for report {ReportId}: {Size} bytes, {ItemCount} items.
        /// </summary>
        internal static string Soc2ReportExporter_CreatedEvidencePackage {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_CreatedEvidencePackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating evidence package for report {ReportId} with {EvidenceCount} items.
        /// </summary>
        internal static string Soc2ReportExporter_CreatingEvidencePackage {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_CreatingEvidencePackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excel export is a basic Open XML implementation. For production, use ClosedXML or EPPlus for better formatting.
        /// </summary>
        internal static string Soc2ReportExporter_ExcelPlaceholder {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_ExcelPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exported report {ReportId} to {Format}: {Size} bytes.
        /// </summary>
        internal static string Soc2ReportExporter_ExportedReport {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_ExportedReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exporting report {ReportId} to {Format}.
        /// </summary>
        internal static string Soc2ReportExporter_ExportingReport {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_ExportingReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDF export is a placeholder. For production, integrate a PDF library like QuestPDF or iTextSharp.
        /// </summary>
        internal static string Soc2ReportExporter_PdfPlaceholder {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_PdfPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report cannot be exported: {Issues}.
        /// </summary>
        internal static string Soc2ReportExporter_ReportNotExportable {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_ReportNotExportable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported export format.
        /// </summary>
        internal static string Soc2ReportExporter_UnsupportedFormat {
            get {
                return ResourceManager.GetString("Soc2ReportExporter_UnsupportedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control validation failure: {ControlId} - {ErrorMessage} (Consecutive failures: {Failures}).
        /// </summary>
        internal static string ComplianceMonitoringService_ControlValidationFailure {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_ControlValidationFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed compliance monitoring cycle. Overall level: {Level}, Gaps: {GapCount}.
        /// </summary>
        internal static string ComplianceMonitoringService_CycleCompleted {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_CycleCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting compliance monitoring cycle.
        /// </summary>
        internal static string ComplianceMonitoringService_CycleStarting {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_CycleStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error in compliance monitoring cycle.
        /// </summary>
        internal static string ComplianceMonitoringService_ErrorInCycle {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_ErrorInCycle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compliance gap alert: {GapId} - {Description} (Severity: {Severity}, Occurrences: {Occurrences}).
        /// </summary>
        internal static string ComplianceMonitoringService_GapAlert {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_GapAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continuous compliance monitoring is disabled.
        /// </summary>
        internal static string ComplianceMonitoringService_MonitoringDisabled {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_MonitoringDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting continuous compliance monitoring with interval {Interval}.
        /// </summary>
        internal static string ComplianceMonitoringService_MonitoringStarting {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_MonitoringStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compliance monitoring service stopped.
        /// </summary>
        internal static string ComplianceMonitoringService_MonitoringStopped {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_MonitoringStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compliance status change detected for {Criterion}: {PreviousStatus} -&gt; {CurrentStatus}.
        /// </summary>
        internal static string ComplianceMonitoringService_StatusChangeDetected {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_StatusChangeDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to get compliance status during monitoring cycle.
        /// </summary>
        internal static string ComplianceMonitoringService_StatusFetchFailed {
            get {
                return ResourceManager.GetString("ComplianceMonitoringService_StatusFetchFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generated Type I report {ReportId} with opinion {Opinion}.
        /// </summary>
        internal static string Soc2ReportGenerator_GeneratedTypeIReport {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_GeneratedTypeIReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generated Type II report {ReportId} with opinion {Opinion}, {ExceptionCount} exceptions.
        /// </summary>
        internal static string Soc2ReportGenerator_GeneratedTypeIIReport {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_GeneratedTypeIIReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating Type I report as of {AsOfDate} for tenant {TenantId}.
        /// </summary>
        internal static string Soc2ReportGenerator_GeneratingTypeIReport {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_GeneratingTypeIReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating Type II report for period {PeriodStart} to {PeriodEnd}, tenant {TenantId}.
        /// </summary>
        internal static string Soc2ReportGenerator_GeneratingTypeIIReport {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_GeneratingTypeIIReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report {ReportId} generated but not stored - no ISoc2ReportStore configured.
        /// </summary>
        internal static string Soc2ReportGenerator_ReportNotStored {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_ReportNotStored", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stored report {ReportId}.
        /// </summary>
        internal static string Soc2ReportGenerator_StoredReport {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_StoredReport", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to PeriodEnd is required for Type II reports.
        /// </summary>
        internal static string Soc2ReportGenerator_PeriodEndRequiredForTypeII {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_PeriodEndRequiredForTypeII", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown report type.
        /// </summary>
        internal static string Soc2ReportGenerator_UnknownReportType {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_UnknownReportType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Period end must be after period start.
        /// </summary>
        internal static string Soc2ReportGenerator_PeriodEndAfterStart {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_PeriodEndAfterStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type II report period must be at least {0} days. Provided period is {1:F0} days.
        /// </summary>
        internal static string Soc2ReportGenerator_TypeIIPeriodTooShort {
            get {
                return ResourceManager.GetString("Soc2ReportGenerator_TypeIIPeriodTooShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatic failover blocked by cooldown. Time remaining: {RemainingSeconds}s.
        /// </summary>
        internal static string MultiRegionKeyProvider_AutoFailoverCooldown {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_AutoFailoverCooldown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AUTOMATIC FAILOVER TRIGGERED. Primary: {PrimaryRegion} (unhealthy, {Failures} consecutive failures) -&gt; Secondary: {SecondaryRegion}.
        /// </summary>
        internal static string MultiRegionKeyProvider_AutoFailoverTriggered {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_AutoFailoverTriggered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MultiRegionKeyProvider disposed.
        /// </summary>
        internal static string MultiRegionKeyProvider_Disposed {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_Disposed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failback completed. Secondary: {SecondaryRegion} -&gt; Primary: {PrimaryRegion}. Reason: {Reason}.
        /// </summary>
        internal static string MultiRegionKeyProvider_FailbackCompleted {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_FailbackCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error during health check cycle.
        /// </summary>
        internal static string MultiRegionKeyProvider_HealthCheckError {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_HealthCheckError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MultiRegionKeyProvider initialized. Primary: {PrimaryRegion}, Secondary: {SecondaryRegion}, Mode: {ReplicationMode}, AutoFailover: {AutoFailover}.
        /// </summary>
        internal static string MultiRegionKeyProvider_Initialized {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_Initialized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key replication completed. Source: {SourceRegion}, Target: {TargetRegion}, KeyId: {KeyId}.
        /// </summary>
        internal static string MultiRegionKeyProvider_KeyReplicationCompleted {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_KeyReplicationCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manual failover initiated. Primary: {PrimaryRegion} -&gt; Secondary: {SecondaryRegion}. Reason: {Reason}.
        /// </summary>
        internal static string MultiRegionKeyProvider_ManualFailoverInitiated {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_ManualFailoverInitiated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replication already in progress, skipping.
        /// </summary>
        internal static string MultiRegionKeyProvider_ReplicationAlreadyInProgress {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_ReplicationAlreadyInProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RPO threshold breached. Current lag: {LagMinutes:F1} minutes, Target: {TargetMinutes:F1} minutes.
        /// </summary>
        internal static string MultiRegionKeyProvider_RpoThresholdBreached {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_RpoThresholdBreached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Syncing keys from {Source} to {Target}. SpecificKey: {KeyId}.
        /// </summary>
        internal static string MultiRegionKeyProvider_SyncingKeys {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_SyncingKeys", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        internal static string AesGcmEncryptionProvider_AuthenticationFailed {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_AuthenticationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encryption key not found..
        /// </summary>
        internal static string AesGcmEncryptionProvider_EncryptionKeyNotFound {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_EncryptionKeyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FIPS compliance is required..
        /// </summary>
        internal static string AesGcmEncryptionProvider_FipsComplianceRequired {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_FipsComplianceRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication tag..
        /// </summary>
        internal static string AesGcmEncryptionProvider_InvalidAuthTag {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_InvalidAuthTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid nonce size. Expected {0} bytes..
        /// </summary>
        internal static string AesGcmEncryptionProvider_InvalidNonceSize {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_InvalidNonceSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key has expired..
        /// </summary>
        internal static string AesGcmEncryptionProvider_KeyExpired {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_KeyExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key material is unavailable..
        /// </summary>
        internal static string AesGcmEncryptionProvider_KeyMaterialUnavailable {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_KeyMaterialUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key status '{0}' does not allow decryption..
        /// </summary>
        internal static string AesGcmEncryptionProvider_KeyStatusNotAllowedForDecryption {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_KeyStatusNotAllowedForDecryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key status '{0}' does not allow encryption..
        /// </summary>
        internal static string AesGcmEncryptionProvider_KeyStatusNotAllowedForEncryption {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_KeyStatusNotAllowedForEncryption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No suitable key found for encryption..
        /// </summary>
        internal static string AesGcmEncryptionProvider_NoSuitableKeyFound {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_NoSuitableKeyFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported encryption algorithm '{0}'..
        /// </summary>
        internal static string AesGcmEncryptionProvider_UnsupportedAlgorithm {
            get {
                return ResourceManager.GetString("AesGcmEncryptionProvider_UnsupportedAlgorithm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported export format '{0}'..
        /// </summary>
        internal static string EncryptionDecryptionService_UnsupportedExportFormat {
            get {
                return ResourceManager.GetString("EncryptionDecryptionService_UnsupportedExportFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No primary provider is configured..
        /// </summary>
        internal static string EncryptionProviderRegistry_NoPrimaryProviderConfigured {
            get {
                return ResourceManager.GetString("EncryptionProviderRegistry_NoPrimaryProviderConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary provider '{0}' was not found..
        /// </summary>
        internal static string EncryptionProviderRegistry_PrimaryProviderNotFound {
            get {
                return ResourceManager.GetString("EncryptionProviderRegistry_PrimaryProviderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider '{0}' is already registered..
        /// </summary>
        internal static string EncryptionProviderRegistry_ProviderAlreadyRegistered {
            get {
                return ResourceManager.GetString("EncryptionProviderRegistry_ProviderAlreadyRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize the encrypted data envelope..
        /// </summary>
        internal static string Encryption_EncryptedDataEnvelopeDeserializeFailed {
            get {
                return ResourceManager.GetString("Encryption_EncryptedDataEnvelopeDeserializeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No primary encryption provider is registered..
        /// </summary>
        internal static string Encryption_NoPrimaryProviderRegistered {
            get {
                return ResourceManager.GetString("Encryption_NoPrimaryProviderRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No provider can decrypt the data..
        /// </summary>
        internal static string Encryption_NoProviderCanDecrypt {
            get {
                return ResourceManager.GetString("Encryption_NoProviderCanDecrypt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No provider can decrypt the data because the key was removed..
        /// </summary>
        internal static string Encryption_NoProviderCanDecryptKeyRemoved {
            get {
                return ResourceManager.GetString("Encryption_NoProviderCanDecryptKeyRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key material has been destroyed..
        /// </summary>
        internal static string InMemoryKeyManagementProvider_KeyMaterialDestroyed {
            get {
                return ResourceManager.GetString("InMemoryKeyManagementProvider_KeyMaterialDestroyed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key not found..
        /// </summary>
        internal static string InMemoryKeyManagementProvider_KeyNotFound {
            get {
                return ResourceManager.GetString("InMemoryKeyManagementProvider_KeyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key version not found..
        /// </summary>
        internal static string InMemoryKeyManagementProvider_KeyVersionNotFound {
            get {
                return ResourceManager.GetString("InMemoryKeyManagementProvider_KeyVersionNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one share is required..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_AtLeastOneShareRequired {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_AtLeastOneShareRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup is at risk: expired or insufficient active shares..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_BackupAtRisk {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_BackupAtRisk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup has expired..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_BackupExpired {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_BackupExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup will expire within 30 days..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_BackupExpiresSoon {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_BackupExpiresSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backup integrity check failed: missing key hash or encrypted data..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_BackupIntegrityCheckFailed {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_BackupIntegrityCheckFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Custodian IDs count must match total shares..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_CustodianIdsCountMismatch {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_CustodianIdsCountMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to decrypt backup..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_DecryptBackupFailed {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_DecryptBackupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insufficient shares: {0} provided, {1} required..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_InsufficientShares {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_InsufficientShares", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key '{0}' already exists..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_KeyAlreadyExists {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_KeyAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key hash verification failed..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_KeyHashVerificationFailed {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_KeyHashVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key hash verification failed after reconstruction..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_KeyHashVerificationFailedAfterReconstruction {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_KeyHashVerificationFailedAfterReconstruction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key '{0}' was not found..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_KeyNotFound {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_KeyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to reconstruct key from shares..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_ReconstructionFailed {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_ReconstructionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share {0} has expired..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_ShareExpired {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_ShareExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All shares must be from the same key..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_SharesKeyMismatch {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_SharesKeyMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All shares must be from the same key version..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_SharesKeyVersionMismatch {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_SharesKeyVersionMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Threshold cannot exceed total shares..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_ThresholdExceedsTotalShares {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_ThresholdExceedsTotalShares", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Threshold must be at least 2..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_ThresholdTooLow {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_ThresholdTooLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total shares must be at least 2..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_TotalSharesTooLow {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_TotalSharesTooLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unsupported backup format version: {0}..
        /// </summary>
        internal static string InMemoryMasterKeyBackupService_UnsupportedFormatVersion {
            get {
                return ResourceManager.GetString("InMemoryMasterKeyBackupService_UnsupportedFormatVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plaintext is empty after decryption..
        /// </summary>
        internal static string ReEncryptionService_EmptyPlaintext {
            get {
                return ResourceManager.GetString("ReEncryptionService_EmptyPlaintext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source provider '{0}' was not found..
        /// </summary>
        internal static string ReEncryptionService_SourceProviderNotFound {
            get {
                return ResourceManager.GetString("ReEncryptionService_SourceProviderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target provider '{0}' was not found..
        /// </summary>
        internal static string ReEncryptionService_TargetProviderNotFound {
            get {
                return ResourceManager.GetString("ReEncryptionService_TargetProviderNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data already encrypted with active key, skipping re-encryption.
        /// </summary>
        internal static string RotatingEncryptionProvider_AlreadyActiveKey {
            get {
                return ResourceManager.GetString("RotatingEncryptionProvider_AlreadyActiveKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key {KeyId} age ({KeyAgeDays:F1} days) exceeds max age ({MaxAgeDays} days), initiating rotation.
        /// </summary>
        internal static string RotatingEncryptionProvider_KeyAgeExceedsMax {
            get {
                return ResourceManager.GetString("RotatingEncryptionProvider_KeyAgeExceedsMax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data encrypted with old key version {KeyId} v{Version}, consider re-encryption.
        /// </summary>
        internal static string RotatingEncryptionProvider_OldKeyVersionReencryptionHint {
            get {
                return ResourceManager.GetString("RotatingEncryptionProvider_OldKeyVersionReencryptionHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Re-encrypted data from key {OldKeyId} v{OldVersion} to {NewKeyId} v{NewVersion}.
        /// </summary>
        internal static string RotatingEncryptionProvider_ReencryptedData {
            get {
                return ResourceManager.GetString("RotatingEncryptionProvider_ReencryptedData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All shares must have the same length..
        /// </summary>
        internal static string ShamirSecretSharing_AllSharesMustHaveSameLength {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_AllSharesMustHaveSameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At least one share is required..
        /// </summary>
        internal static string ShamirSecretSharing_AtLeastOneShareRequired {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_AtLeastOneShareRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot divide by zero in GF(256)..
        /// </summary>
        internal static string ShamirSecretSharing_CannotDivideByZero {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_CannotDivideByZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate share indices detected..
        /// </summary>
        internal static string ShamirSecretSharing_DuplicateShareIndicesDetected {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_DuplicateShareIndicesDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share index cannot be 0..
        /// </summary>
        internal static string ShamirSecretSharing_ShareIndexCannotBeZero {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_ShareIndexCannotBeZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shares must have at least 2 bytes (index + data)..
        /// </summary>
        internal static string ShamirSecretSharing_SharesMustHaveAtLeastTwoBytes {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_SharesMustHaveAtLeastTwoBytes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Threshold must be at least 2..
        /// </summary>
        internal static string ShamirSecretSharing_ThresholdAtLeastTwo {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_ThresholdAtLeastTwo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Threshold ({0}) cannot exceed total shares ({1})..
        /// </summary>
        internal static string ShamirSecretSharing_ThresholdExceedsTotalShares {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_ThresholdExceedsTotalShares", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total shares must be at least 2..
        /// </summary>
        internal static string ShamirSecretSharing_TotalSharesAtLeastTwo {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_TotalSharesAtLeastTwo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total shares cannot exceed 255 (GF(256) limitation)..
        /// </summary>
        internal static string ShamirSecretSharing_TotalSharesCannotExceedLimit {
            get {
                return ResourceManager.GetString("ShamirSecretSharing_TotalSharesCannotExceedLimit", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to TableName is required.
        /// </summary>
        internal static string DataInventoryService_TableNameRequired {
            get {
                return ResourceManager.GetString("DataInventoryService_TableNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FieldName is required.
        /// </summary>
        internal static string DataInventoryService_FieldNameRequired {
            get {
                return ResourceManager.GetString("DataInventoryService_FieldNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataCategory is required.
        /// </summary>
        internal static string DataInventoryService_DataCategoryRequired {
            get {
                return ResourceManager.GetString("DataInventoryService_DataCategoryRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataSubjectIdColumn is required.
        /// </summary>
        internal static string DataInventoryService_DataSubjectIdColumnRequired {
            get {
                return ResourceManager.GetString("DataInventoryService_DataSubjectIdColumnRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KeyIdColumn is required.
        /// </summary>
        internal static string DataInventoryService_KeyIdColumnRequired {
            get {
                return ResourceManager.GetString("DataInventoryService_KeyIdColumnRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legal hold {0} not found.
        /// </summary>
        internal static string LegalHoldService_HoldNotFound {
            get {
                return ResourceManager.GetString("LegalHoldService_HoldNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Legal hold {0} is already released.
        /// </summary>
        internal static string LegalHoldService_HoldAlreadyReleased {
            get {
                return ResourceManager.GetString("LegalHoldService_HoldAlreadyReleased", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Either DataSubjectId or TenantId must be specified for a legal hold.
        /// </summary>
        internal static string LegalHoldService_HoldSubjectOrTenantRequired {
            get {
                return ResourceManager.GetString("LegalHoldService_HoldSubjectOrTenantRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CaseReference is required.
        /// </summary>
        internal static string LegalHoldService_CaseReferenceRequired {
            get {
                return ResourceManager.GetString("LegalHoldService_CaseReferenceRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string LegalHoldService_DescriptionRequired {
            get {
                return ResourceManager.GetString("LegalHoldService_DescriptionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CreatedBy is required.
        /// </summary>
        internal static string LegalHoldService_CreatedByRequired {
            get {
                return ResourceManager.GetString("LegalHoldService_CreatedByRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ExpiresAt must be in the future.
        /// </summary>
        internal static string LegalHoldService_ExpiresAtMustBeFuture {
            get {
                return ResourceManager.GetString("LegalHoldService_ExpiresAtMustBeFuture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erasure request {0} cannot be cancelled. Status: {1}.
        /// </summary>
        internal static string ErasureService_CannotCancelRequest {
            get {
                return ResourceManager.GetString("ErasureService_CannotCancelRequest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Erasure request {0} not found.
        /// </summary>
        internal static string ErasureService_RequestNotFound {
            get {
                return ResourceManager.GetString("ErasureService_RequestNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot generate certificate for request {0}. Status: {1}.
        /// </summary>
        internal static string ErasureService_CannotGenerateCertificate {
            get {
                return ResourceManager.GetString("ErasureService_CannotGenerateCertificate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataSubjectId is required.
        /// </summary>
        internal static string ErasureService_DataSubjectIdRequired {
            get {
                return ResourceManager.GetString("ErasureService_DataSubjectIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RequestedBy is required.
        /// </summary>
        internal static string ErasureService_RequestedByRequired {
            get {
                return ResourceManager.GetString("ErasureService_RequestedByRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TenantId is required for Tenant scope.
        /// </summary>
        internal static string ErasureService_TenantIdRequiredForScope {
            get {
                return ResourceManager.GetString("ErasureService_TenantIdRequiredForScope", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DataCategories must be specified for Selective scope.
        /// </summary>
        internal static string ErasureService_DataCategoriesRequired {
            get {
                return ResourceManager.GetString("ErasureService_DataCategoriesRequired", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Already in failover mode. Use FailbackToPrimaryAsync to return to primary..
        /// </summary>
        internal static string MultiRegionKeyProvider_AlreadyInFailoverMode {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_AlreadyInFailoverMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not in failover mode. Cannot failback..
        /// </summary>
        internal static string MultiRegionKeyProvider_NotInFailoverMode {
            get {
                return ResourceManager.GetString("MultiRegionKeyProvider_NotInFailoverMode", resourceCulture);
            }
        }
    }
}
