#!/usr/bin/env python3
"""Regenerate eng/reports/ci-workflow-inventory.md from the workflows themselves.

This exists because nothing described what CI actually runs, so "which checks are required"
had no answer anyone could read, and 21 workflows could overlap without it being visible.
The document is generated, never hand-edited: a hand-maintained inventory drifts, and a drifted
inventory is worse than none because it is trusted.

Usage:  python3 eng/ci/generate-workflow-inventory.py [--check]
        --check exits 1 if the committed document is stale.
"""
import sys, glob, io, os

def build():
    import yaml
    rows = []
    for f in sorted(glob.glob('.github/workflows/*.yml')):
        b = os.path.basename(f)
        d = yaml.safe_load(io.open(f, encoding='utf-8'))
        trig = d.get(True) or d.get('on') or {}
        tk = ','.join(trig.keys()) if isinstance(trig, dict) else str(trig)
        perms = d.get('permissions')
        for jn, j in (d.get('jobs') or {}).items():
            txt = str(j)
            rows.append(dict(
                wf=b, job=jn, trig=tk, wall=j.get('timeout-minutes'),
                runs=str(j.get('runs-on', '')),
                needs=','.join(j.get('needs') or []) if isinstance(j.get('needs'), list) else str(j.get('needs') or ''),
                tests=('dotnet test' in txt or 'run-filtered-tests' in txt),
                builds=('dotnet build' in txt),
                perms=('job' if j.get('permissions') else ('workflow' if perms is not None else 'INHERITED')),
                coe=bool(j.get('continue-on-error'))))
    wfs = len(set(r['wf'] for r in rows))
    out = ["# CI/CD workflow inventory", "",
           "> Generated by `eng/ci/generate-workflow-inventory.py`. Do not edit by hand -- regenerate.",
           "> Every workflow, every job, one row.", "",
           f"**{wfs} workflows, {len(rows)} jobs.** "
           f"{sum(1 for r in rows if r['tests'])} run tests; {sum(1 for r in rows if r['builds'])} build; "
           f"{sum(1 for r in rows if r['perms'] == 'INHERITED')} inherit token permissions; "
           f"{sum(1 for r in rows if r['coe'])} are soft (continue-on-error).", "",
           "A job with no wall is a `uses:` call into a reusable workflow, where GitHub does not",
           "permit `timeout-minutes`; the called workflow's own job timeouts apply.", "",
           "| workflow | job | triggers | wall | runs-on | needs | tests | perms | soft |",
           "|---|---|---|---|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda x: (x['wf'], x['job'])):
        out.append(f"| {r['wf']} | {r['job']} | {r['trig']} | {r['wall'] or '-'} | {r['runs'][:26]} | "
                   f"{r['needs'][:34] or '-'} | {'yes' if r['tests'] else ''} | {r['perms']} | "
                   f"{'yes' if r['coe'] else ''} |")
    return '\n'.join(out) + '\n'

DOC = 'eng/reports/ci-workflow-inventory.md'
try:
    content = build()
except ImportError:
    print("REFUSE: PyYAML unavailable; cannot generate. This is NOT a pass.", file=sys.stderr); sys.exit(2)

if '--check' in sys.argv:
    cur = io.open(DOC, encoding='utf-8').read() if os.path.exists(DOC) else ''
    if cur != content:
        print(f"::error::{DOC} is stale. Run: python3 eng/ci/generate-workflow-inventory.py", file=sys.stderr)
        sys.exit(1)
    print(f"{DOC} is current."); sys.exit(0)

io.open(DOC, 'w', encoding='utf-8', newline='\n').write(content)
print(f"wrote {DOC}")
