// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Excalibur.Dispatch.Security.Tests.Compliance.Configuration;

/// <summary>
/// Unit tests for <see cref="EncryptionServiceCollectionExtensions"/>.
/// </summary>
[Trait("Category", TestCategories.Unit)]
public sealed class EncryptionServiceCollectionExtensionsShould
{
	#region AddEncryption Tests

	[Fact]
	public void AddEncryption_RegisterRegistryAsSingleton()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		_ = services.AddEncryption(builder => builder
			.UseInMemoryKeyManagement("test-provider"));

		// Assert
		var provider = services.BuildServiceProvider();
		var registry1 = provider.GetRequiredService<IEncryptionProviderRegistry>();
		var registry2 = provider.GetRequiredService<IEncryptionProviderRegistry>();

		registry1.ShouldBeSameAs(registry2);
	}

	[Fact]
	public void AddEncryption_ReturnServicesForChaining()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		var result = services.AddEncryption(builder => builder
			.UseInMemoryKeyManagement());

		// Assert
		result.ShouldBeSameAs(services);
	}

	[Fact]
	public void AddEncryption_ThrowArgumentNullException_WhenServicesIsNull()
	{
		// Arrange
		IServiceCollection? services = null;

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddEncryption(builder => builder.UseInMemoryKeyManagement()));
	}

	[Fact]
	public void AddEncryption_ThrowArgumentNullException_WhenConfigureIsNull()
	{
		// Arrange
		var services = new ServiceCollection();

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddEncryption(null!));
	}

	#endregion AddEncryption Tests

	#region AddDevEncryption Tests

	[Fact]
	public void AddDevEncryption_RegisterInMemoryProvider()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		_ = services.AddDevEncryption();

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();

		_ = registry.ShouldNotBeNull();
	}

	[Fact]
	public void AddDevEncryption_RegisterWarningLogger()
	{
		// Arrange
		var services = new ServiceCollection();
		var loggerCalled = false;

		// Register a custom logger that captures warning calls
		// We need to register the typed logger directly because ILogger<T> resolution
		// doesn't go through ILoggerFactory in Microsoft.Extensions.DependencyInjection
		_ = services.AddSingleton<ILogger<DevEncryptionWarningLogger>>(
			new TestLogger<DevEncryptionWarningLogger>(() => loggerCalled = true));

		// Still need ILoggerFactory for other services
		_ = services.AddSingleton<ILoggerFactory>(NullLoggerFactory.Instance);
		_ = services.AddSingleton(typeof(ILogger<>), typeof(NullLogger<>));

		// Act
		_ = services.AddDevEncryption();

		// Assert
		var provider = services.BuildServiceProvider();
		// Resolve the warning logger to trigger the warning
		_ = provider.GetRequiredService<DevEncryptionWarningLogger>();

		loggerCalled.ShouldBeTrue();
	}

	[Fact]
	public void AddDevEncryption_ReturnServicesForChaining()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		var result = services.AddDevEncryption();

		// Assert
		result.ShouldBeSameAs(services);
	}

	[Fact]
	public void AddDevEncryption_ThrowArgumentNullException_WhenServicesIsNull()
	{
		// Arrange
		IServiceCollection? services = null;

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddDevEncryption());
	}

	[Fact]
	public void AddDevEncryption_ConfigureWithAutoGenerateDefaultKey()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		_ = services.AddDevEncryption();

		// Assert
		var provider = services.BuildServiceProvider();
		var options = provider.GetService<InMemoryKeyManagementOptions>();

		_ = options.ShouldNotBeNull();
		options.AutoGenerateDefaultKey.ShouldBeTrue();
	}

	#endregion AddDevEncryption Tests

	#region Helper Classes

	/// <summary>
	/// Adds test logging to the service collection using NullLoggerFactory.
	/// </summary>
	private static void AddTestLogging(IServiceCollection services)
	{
		_ = services.AddSingleton<ILoggerFactory>(NullLoggerFactory.Instance);
		_ = services.AddSingleton(typeof(ILogger<>), typeof(NullLogger<>));
	}

	private sealed class TestLoggerFactory(Action onWarning) : ILoggerFactory
	{
		public void AddProvider(ILoggerProvider provider)
		{ }

		public ILogger CreateLogger(string categoryName) =>
			new TestLogger(onWarning);

		public void Dispose()
		{ }
	}

	private sealed class TestLogger(Action onWarning) : ILogger
	{
		public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

		public bool IsEnabled(LogLevel logLevel) => true;

		public void Log<TState>(
			LogLevel logLevel,
			EventId eventId,
			TState state,
			Exception? exception,
			Func<TState, Exception?, string> formatter)
		{
			if (logLevel == LogLevel.Warning)
			{
				onWarning();
			}
		}
	}

	private sealed class TestLogger<T>(Action onWarning) : ILogger<T>
	{
		public IDisposable? BeginScope<TState>(TState state) where TState : notnull => null;

		public bool IsEnabled(LogLevel logLevel) => true;

		public void Log<TState>(
			LogLevel logLevel,
			EventId eventId,
			TState state,
			Exception? exception,
			Func<TState, Exception?, string> formatter)
		{
			if (logLevel == LogLevel.Warning)
			{
				onWarning();
			}
		}
	}

	#endregion Helper Classes
}
