// SPDX-FileCopyrightText: Copyright (c) 2026 The Excalibur Project
// SPDX-License-Identifier: LicenseRef-Excalibur-1.0 OR AGPL-3.0-or-later OR SSPL-1.0 OR Apache-2.0

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Excalibur.Dispatch.Security.Tests.Compliance.Configuration;

/// <summary>
/// Unit tests for <see cref="EncryptionConfigurationBuilder"/>.
/// </summary>
[Trait("Category", TestCategories.Unit)]
public sealed class EncryptionConfigurationBuilderShould
{
	#region UseInMemoryKeyManagement Tests

	[Fact]
	public void UseInMemoryKeyManagement_RegisterProviderSuccessfully()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		_ = services.AddEncryption(builder => builder
			.UseInMemoryKeyManagement("test-inmemory"));

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();

		// Resolve encryption providers to trigger registration callbacks
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		_ = registry.GetProvider("test-inmemory").ShouldNotBeNull();
	}

	[Fact]
	public void UseInMemoryKeyManagement_SetFirstProviderAsPrimary()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		_ = services.AddEncryption(builder => builder
			.UseInMemoryKeyManagement("primary-provider"));

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();

		// Resolve all encryption providers to trigger registration
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		_ = registry.GetPrimary().ShouldNotBeNull();
	}

	[Fact]
	public void UseInMemoryKeyManagement_GenerateUniqueIdWhenNotProvided()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);

		// Act
		_ = services.AddEncryption(builder => builder
			.UseInMemoryKeyManagement()); // No providerId specified

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		registry.GetAll().Count.ShouldBeGreaterThanOrEqualTo(1);
	}

	[Fact]
	public void UseInMemoryKeyManagement_ApplyConfigurationAction()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var optionsCaptured = false;

		// Act
		_ = services.AddEncryption(builder => builder
			.UseInMemoryKeyManagement("test", options =>
			{
				options.AutoGenerateDefaultKey = false;
				options.DefaultKeyId = "custom-key";
				optionsCaptured = true;
			}));

		// Assert
		optionsCaptured.ShouldBeTrue();
	}

	#endregion UseInMemoryKeyManagement Tests

	#region UseKeyManagement<T> Tests

	[Fact]
	public void UseKeyManagement_RegisterCustomProviderType()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		_ = services.AddSingleton(A.Fake<IKeyManagementProvider>());

		// Act
		_ = services.AddEncryption(builder => builder
			.UseKeyManagement<AesGcmEncryptionProvider>("custom-aes"));

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		_ = registry.GetProvider("custom-aes").ShouldNotBeNull();
	}

	#endregion UseKeyManagement<T> Tests

	#region UseProvider Tests

	[Fact]
	public void UseProvider_RegisterInstanceSuccessfully()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act
		_ = services.AddEncryption(builder => builder
			.UseProvider("instance-provider", mockProvider));

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		registry.GetProvider("instance-provider").ShouldBe(mockProvider);
	}

	[Fact]
	public void UseProvider_ThrowArgumentNullException_WhenProviderIdIsNull()
	{
		// Arrange
		var services = new ServiceCollection();
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddEncryption(builder => builder
				.UseProvider(null!, mockProvider)));
	}

	[Fact]
	public void UseProvider_ThrowArgumentNullException_WhenProviderIsNull()
	{
		// Arrange
		var services = new ServiceCollection();

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddEncryption(builder => builder
				.UseProvider("test", null!)));
	}

	#endregion UseProvider Tests

	#region SetAsPrimary Tests

	[Fact]
	public void SetAsPrimary_ChangePrimaryProvider()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var mockProvider1 = A.Fake<IEncryptionProvider>();
		var mockProvider2 = A.Fake<IEncryptionProvider>();

		// Act
		_ = services.AddEncryption(builder => builder
			.UseProvider("provider-1", mockProvider1)
			.UseProvider("provider-2", mockProvider2)
			.SetAsPrimary("provider-2"));

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		registry.GetPrimary().ShouldBe(mockProvider2);
	}

	[Fact]
	public void SetAsPrimary_ThrowArgumentNullException_WhenProviderIdIsNull()
	{
		// Arrange
		var services = new ServiceCollection();
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddEncryption(builder => builder
				.UseProvider("test", mockProvider)
				.SetAsPrimary(null!)));
	}

	[Fact]
	public void SetAsPrimary_ThrowInvalidOperationException_WhenProviderNotRegistered()
	{
		// Arrange
		var services = new ServiceCollection();
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act & Assert
		var ex = Should.Throw<InvalidOperationException>(() =>
			services.AddEncryption(builder => builder
				.UseProvider("test", mockProvider)
				.SetAsPrimary("non-existent")));

		ex.Message.ShouldContain("non-existent");
		ex.Message.ShouldContain("was not registered");
	}

	#endregion SetAsPrimary Tests

	#region AddLegacy Tests

	[Fact]
	public void AddLegacy_MarkProviderAsLegacy()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var primaryProvider = A.Fake<IEncryptionProvider>();
		var legacyProvider = A.Fake<IEncryptionProvider>();

		// Act
		_ = services.AddEncryption(builder => builder
			.UseProvider("primary", primaryProvider)
			.UseProvider("legacy", legacyProvider)
			.AddLegacy("legacy"));

		// Assert
		var provider = services.BuildServiceProvider();
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		registry.GetLegacyProviders().ShouldContain(legacyProvider);
	}

	[Fact]
	public void AddLegacy_ThrowArgumentNullException_WhenProviderIdIsNull()
	{
		// Arrange
		var services = new ServiceCollection();
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddEncryption(builder => builder
				.UseProvider("test", mockProvider)
				.AddLegacy(null!)));
	}

	[Fact]
	public void AddLegacy_ThrowInvalidOperationException_WhenProviderNotRegistered()
	{
		// Arrange
		var services = new ServiceCollection();
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act & Assert
		var ex = Should.Throw<InvalidOperationException>(() =>
			services.AddEncryption(builder => builder
				.UseProvider("test", mockProvider)
				.AddLegacy("non-existent")));

		ex.Message.ShouldContain("non-existent");
		ex.Message.ShouldContain("was not registered");
	}

	#endregion AddLegacy Tests

	#region ConfigureOptions Tests

	[Fact]
	public void ConfigureOptions_RegisterOptions()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act
		_ = services.AddEncryption(builder => builder
			.UseProvider("test", mockProvider)
			.ConfigureOptions(options =>
			{
				options.RequireFipsCompliance = true;
				options.DefaultPurpose = "custom-purpose";
			}));

		// Assert
		var provider = services.BuildServiceProvider();
		var options = provider.GetRequiredService<Dispatch.Compliance.EncryptionOptions>();

		options.RequireFipsCompliance.ShouldBeTrue();
		options.DefaultPurpose.ShouldBe("custom-purpose");
	}

	[Fact]
	public void ConfigureOptions_ThrowArgumentNullException_WhenConfigureIsNull()
	{
		// Arrange
		var services = new ServiceCollection();
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act & Assert
		_ = Should.Throw<ArgumentNullException>(() =>
			services.AddEncryption(builder => builder
				.UseProvider("test", mockProvider)
				.ConfigureOptions(null!)));
	}

	#endregion ConfigureOptions Tests

	#region Method Chaining Tests

	[Fact]
	public void MethodChaining_ReturnBuilderForFluency()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var mockProvider = A.Fake<IEncryptionProvider>();

		// Act - all methods should return the builder for chaining
		_ = services.AddEncryption(builder =>
		{
			var b1 = builder.UseInMemoryKeyManagement("p1");
			var b2 = b1.UseProvider("p2", mockProvider);
			var b3 = b2.SetAsPrimary("p2");
			var b4 = b3.AddLegacy("p1");
			var b5 = b4.ConfigureOptions(o => o.DefaultPurpose = "test");

			// All should be the same builder instance
			b1.ShouldBe(builder);
			b2.ShouldBe(builder);
			b3.ShouldBe(builder);
			b4.ShouldBe(builder);
			b5.ShouldBe(builder);
		});
	}

	#endregion Method Chaining Tests

	#region Validation Tests

	[Fact]
	public void Validate_ThrowInvalidOperationException_WhenNoProvidersRegistered()
	{
		// Arrange
		var services = new ServiceCollection();

		// Act & Assert
		var ex = Should.Throw<InvalidOperationException>(() =>
			services.AddEncryption(builder => { /* No providers registered */ }));

		ex.Message.ShouldContain("No encryption providers were registered");
	}

	#endregion Validation Tests

	#region Integration Tests

	[Fact]
	public void FullConfiguration_WorksEndToEnd()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var legacyProvider = A.Fake<IEncryptionProvider>();

		// Act
		_ = services.AddEncryption(builder => builder
			.UseInMemoryKeyManagement("primary-provider")
			.UseProvider("legacy-provider", legacyProvider)
			.SetAsPrimary("primary-provider")
			.AddLegacy("legacy-provider")
			.ConfigureOptions(options =>
			{
				options.RequireFipsCompliance = false;
				options.DefaultPurpose = "integration-test";
			}));

		// Assert
		var provider = services.BuildServiceProvider();

		// Verify registry registration
		var registry = provider.GetRequiredService<IEncryptionProviderRegistry>();
		_ = registry.ShouldNotBeNull();

		// Resolve all providers to trigger registration
		_ = provider.GetServices<IEncryptionProvider>().ToList();
		_ = provider.GetService<IEncryptionProviderInitializer>();

		// Verify providers are registered
		_ = registry.GetProvider("primary-provider").ShouldNotBeNull();
		registry.GetProvider("legacy-provider").ShouldBe(legacyProvider);

		// Verify primary is set correctly
		_ = registry.GetPrimary().ShouldNotBeNull();

		// Verify legacy is marked
		registry.GetLegacyProviders().ShouldContain(legacyProvider);

		// Verify options are set
		var options = provider.GetRequiredService<Dispatch.Compliance.EncryptionOptions>();
		options.RequireFipsCompliance.ShouldBeFalse();
		options.DefaultPurpose.ShouldBe("integration-test");
	}

	[Fact]
	public void MultipleProviders_AllRegistered()
	{
		// Arrange
		var services = new ServiceCollection();
		AddTestLogging(services);
		var provider1 = A.Fake<IEncryptionProvider>();
		var provider2 = A.Fake<IEncryptionProvider>();
		var provider3 = A.Fake<IEncryptionProvider>();

		// Act
		_ = services.AddEncryption(builder => builder
			.UseProvider("provider-1", provider1)
			.UseProvider("provider-2", provider2)
			.UseProvider("provider-3", provider3));

		// Assert
		var sp = services.BuildServiceProvider();
		var registry = sp.GetRequiredService<IEncryptionProviderRegistry>();
		_ = sp.GetServices<IEncryptionProvider>().ToList();
		_ = sp.GetService<IEncryptionProviderInitializer>();

		registry.GetAll().Count.ShouldBe(3);
		registry.GetProvider("provider-1").ShouldBe(provider1);
		registry.GetProvider("provider-2").ShouldBe(provider2);
		registry.GetProvider("provider-3").ShouldBe(provider3);
	}

	#endregion Integration Tests

	#region Helpers

	/// <summary>
	/// Adds test logging to the service collection using NullLoggerFactory.
	/// </summary>
	private static void AddTestLogging(IServiceCollection services)
	{
		_ = services.AddSingleton<ILoggerFactory>(NullLoggerFactory.Instance);
		_ = services.AddSingleton(typeof(ILogger<>), typeof(NullLogger<>));
	}

	#endregion Helpers
}
