//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excalibur.Saga {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excalibur.Saga.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition must be specified..
        /// </summary>
        internal static string ConditionalStepBuilder_ConditionMustBeSpecified {
            get {
                return ResourceManager.GetString("ConditionalStepBuilder_ConditionMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one branch must be specified..
        /// </summary>
        internal static string MultiConditionalStepBuilder_AtLeastOneBranchMustBeSpecified {
            get {
                return ResourceManager.GetString("MultiConditionalStepBuilder_AtLeastOneBranchMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch evaluator must be specified..
        /// </summary>
        internal static string MultiConditionalStepBuilder_BranchEvaluatorMustBeSpecified {
            get {
                return ResourceManager.GetString("MultiConditionalStepBuilder_BranchEvaluatorMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch key cannot be null or whitespace..
        /// </summary>
        internal static string MultiConditionalStepBuilder_BranchKeyCannotBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("MultiConditionalStepBuilder_BranchKeyCannotBeNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler type must have exactly 2 generic arguments..
        /// </summary>
        internal static string ProcessManager_HandlerTypeMustHaveExactlyTwoGenericArguments {
            get {
                return ResourceManager.GetString("ProcessManager_HandlerTypeMustHaveExactlyTwoGenericArguments", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Timeout store not configured. Register ISagaTimeoutStore in the DI container..
        /// </summary>
        internal static string SagaBase_TimeoutStoreNotConfigured {
            get {
                return ResourceManager.GetString("SagaBase_TimeoutStoreNotConfigured", resourceCulture);
            }
        }
    }
}

