-- MOVED. This file no longer contains schema, and it is kept only so that a consumer who has this
-- path bookmarked, or who provisioned from it previously, is told where the schema went rather than
-- finding it silently deleted.
--
-- Excalibur.Dispatch is the messaging core. It contains no SQL dead-letter store — only the
-- in-memory one — so it was shipping DDL for tables that live in, and are written by, other
-- packages. That split is what let the two halves drift apart unnoticed. Each definition now ships
-- from the package that owns the store, so the DDL and the statements it has to satisfy version
-- together:
--
--     SQL Server   ->  Excalibur.Data.SqlServer, scripts/001_CreateDeadLetterSchema.sql
--                      creates [dbo].[DeadLetterMessages]
--
--     PostgreSQL   ->  Excalibur.Data.Postgres,  scripts/001_CreateDeadLetterSchema.sql
--                      creates "public"."dead_letter_messages"
--
-- Both are packed into their package under scripts/, so `nuget install` or an unzip of the .nupkg
-- puts them on disk.
--
-- IF YOU PROVISIONED FROM THE OLD COPY OF THIS FILE, READ THIS.
--
-- SQL Server: the definition moved unchanged. The replacement script is guarded throughout, so
-- running it against a database created from the old copy is a no-op on the table and still applies
-- the additive tenant-column and collation upgrades. Nothing needs undoing.
--
-- PostgreSQL: you did not provision from this file, whatever the file appeared to offer. The
-- PostgreSQL definition it carried sat entirely inside a /* ... */ comment, in a file that is
-- otherwise SQL Server dialect and batch-separated by GO. Running it against PostgreSQL creates
-- nothing and cannot get that far — it fails at the first GO. If you believed this table existed,
-- check for it before your next dead-letter write rather than after; the schema is now real and
-- executable at the path above.
