//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excalibur.Compliance.SqlServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excalibur.Compliance.SqlServer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificatesTableName cannot be empty.
        /// </summary>
        internal static string SqlServerErasureStoreOptions_CertificatesTableNameEmpty {
            get {
                return ResourceManager.GetString("SqlServerErasureStoreOptions_CertificatesTableNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandTimeoutSeconds must be positive.
        /// </summary>
        internal static string SqlServerErasureStoreOptions_CommandTimeoutPositive {
            get {
                return ResourceManager.GetString("SqlServerErasureStoreOptions_CommandTimeoutPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString is required for SQL Server erasure store.
        /// </summary>
        internal static string SqlServerErasureStoreOptions_ConnectionStringRequired {
            get {
                return ResourceManager.GetString("SqlServerErasureStoreOptions_ConnectionStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestsTableName cannot be empty.
        /// </summary>
        internal static string SqlServerErasureStoreOptions_RequestsTableNameEmpty {
            get {
                return ResourceManager.GetString("SqlServerErasureStoreOptions_RequestsTableNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemaName cannot be empty.
        /// </summary>
        internal static string SqlServerErasureStoreOptions_SchemaNameEmpty {
            get {
                return ResourceManager.GetString("SqlServerErasureStoreOptions_SchemaNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active escrow not found for key {0}.
        /// </summary>
        internal static string SqlServerKeyEscrowService_ActiveEscrowNotFound {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_ActiveEscrowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate tokens for non-recoverable escrow (state: {0}).
        /// </summary>
        internal static string SqlServerKeyEscrowService_CannotGenerateTokensForState {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_CannotGenerateTokensForState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is required.
        /// </summary>
        internal static string SqlServerKeyEscrowService_ConnectionStringRequired {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_ConnectionStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian count must be at least 2.
        /// </summary>
        internal static string SqlServerKeyEscrowService_CustodianCountTooLow {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_CustodianCountTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escrow for key {0} is not recoverable (state: {1}).
        /// </summary>
        internal static string SqlServerKeyEscrowService_EscrowNotRecoverable {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_EscrowNotRecoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} shares required for recovery, but only {1} provided.
        /// </summary>
        internal static string SqlServerKeyEscrowService_InsufficientShares {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_InsufficientShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key material cannot be empty.
        /// </summary>
        internal static string SqlServerKeyEscrowService_KeyMaterialEmpty {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_KeyMaterialEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No escrow found for key {0}.
        /// </summary>
        internal static string SqlServerKeyEscrowService_NoEscrowFound {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_NoEscrowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery token has expired.
        /// </summary>
        internal static string SqlServerKeyEscrowService_RecoveryTokenExpired {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_RecoveryTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold cannot exceed custodian count.
        /// </summary>
        internal static string SqlServerKeyEscrowService_ThresholdTooHigh {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_ThresholdTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold must be at least 2.
        /// </summary>
        internal static string SqlServerKeyEscrowService_ThresholdTooLow {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_ThresholdTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token escrow ID does not match.
        /// </summary>
        internal static string SqlServerKeyEscrowService_TokenEscrowIdMismatch {
            get {
                return ResourceManager.GetString("SqlServerKeyEscrowService_TokenEscrowIdMismatch", resourceCulture);
            }
        }
    }
}
