name: Publish

on:
    push:
        branches:
            - main
            - develop
            - feature/*
            - release/*
            - hotfix/*
    pull_request:

env:
    IS_RELEASE: false
    IS_PRERELEASE: false
    PUBLISH: false

jobs:
    build-and-publish:
        runs-on: windows-latest

        steps:
            - name: Determine if release or prerelease
              id: determine_release
              run: |
                  $branch = "${{ github.ref_name }}"
                  if ($branch -eq "main" -or $branch -eq "master") {
                      echo "IS_RELEASE=true" >> $GITHUB_ENV
                  } elseif ($branch -like "release/*") {
                      echo "IS_PRERELEASE=true" >> $GITHUB_ENV
                  }

                  if ($env:IS_RELEASE -eq "true" -or $env:IS_PRERELEASE -eq "true") {
                      if ($github.event_name -ne 'pull_request') {
                          echo "PUBLISH=true" >> $GITHUB_ENV
                      }
                  }
              shell: powershell

            # Step 1: Check out the code
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # Step 2: Setup .NET
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x"

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v3.1.2
              with:
                  versionSpec: "6.0.x"
                  preferLatestVersion: true

            # Step 3: GitVersion
            # This action will read GitVersion.yml, look at commits & branches,
            # and produce a semantic version (e.g., 1.2.3, 1.2.3-beta.1, etc.)
            - name: Determine version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v3.1.2
              with:
                  useConfigFile: true
                  updateAssemblyInfo: true

            - name: Set Release Version
              id: set_release_version
              run: |
                  if ($env:IS_RELEASE -eq "true") {
                    echo "version=${{ steps.gitversion.outputs.MajorMinorPatch }}" >> $GITHUB_ENV
                  } else {
                    echo "version=${{ steps.gitversion.outputs.SemVer }}" >> $GITHUB_ENV
                  }
                  echo "version=$env:version" >> $GITHUB_OUTPUT
              shell: powershell

            - name: Set GitVersion Variables
              run: |
                  echo "GitVersion_NuGetVersion=${{ steps.set_release_version.outputs.version }}" >> $GITHUB_ENV
                  echo "GitVersion_AssemblySemVer=${{ steps.gitversion.outputs.AssemblySemVer }}" >> $GITHUB_ENV
                  echo "GitVersion_AssemblySemFileVer=${{ steps.gitversion.outputs.AssemblySemFileVer }}" >> $GITHUB_ENV
                  echo "GitVersion_InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}" >> $GITHUB_ENV

            # Step 4: Build
            - name: Restore .NET dependencies
              run: dotnet restore

            - name: Build .NET solution
              run: dotnet build --configuration Release

            - name: Run tests
              run: dotnet test --configuration Release

            # Step 5: Replace <ProjectReference> with <PackageReference>
            - name: Replace ProjectReferences
              if: env.PUBLISH == 'true'
              run: |
                  $env:PACKAGE_VERSION = $env:GitVersion_NuGetVersion
                  Write-Host "Using GitVersion's NuGetVersion: $($env:GitVersion_NuGetVersion)"
                  powershell -ExecutionPolicy Bypass -File scripts/ReplaceProjectReferences.ps1
              shell: powershell

            # Step 6: Pack .csproj files using GitVersion's SemVer
            - name: Create NuGet packages
              if: env.PUBLISH == 'true'
              run: |
                  Write-Host "Packing projects with PackageVersion: $env:GitVersion_NuGetVersion"
                  Write-Host "Packing projects with Version: $env:GitVersion_InformationalVersion"

                  $artifactPath = Join-Path $env:GITHUB_WORKSPACE 'artifacts'

                  if (-Not (Test-Path $artifactPath)) {
                    New-Item -ItemType Directory -Path $artifactPath | Out-Null
                  }

                  $csprojFiles = Get-ChildItem -Path . -Recurse -Filter *.csproj
                  foreach ($file in $csprojFiles) {
                      dotnet pack $file.FullName `
                        --configuration Release `
                        -p:PackageVersion=$env:GitVersion_NuGetVersion `
                        -p:Version=$env:GitVersion_NuGetVersion `
                        --no-build `
                        --output $artifactPath
                  }
              shell: powershell

            # Step 7: Publish NuGet packages.
            - name: Publish NuGet packages
              if: env.PUBLISH == 'true'
              run: |
                  $env:NUGET_API_KEY = "${{ secrets.NUGET_API_KEY }}"
                  $artifactPath = Join-Path $env:GITHUB_WORKSPACE 'artifacts'
                  $packages = Get-ChildItem $artifactPath -Filter *.nupkg

                  foreach ($pkg in $packages) {
                      Write-Host "Publishing package: $($pkg.FullName)"
                      dotnet nuget push $pkg.FullName `
                        --api-key $env:NUGET_API_KEY `
                        --source https://api.nuget.org/v3/index.json `
                        --skip-duplicate
                  }
              shell: powershell

            # Step 8: Create Release.
            - name: Create GitHub Release
              if: env.PUBLISH == 'true'
              id: create_release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: v$env:version
                  name: Release v$env:version
                  body: "Automated release based on commit history."
                  prerelease: $env:IS_PRERELEASE -eq "true"
                  generate_release_notes: true
                  files: |
                      artifacts/*.nupkg
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
