name: Sync main to develop

on:
    workflow_run:
        workflows: ["Publish"]
        types: [completed]

jobs:
    sync-branches:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}

        steps:
            - name: Check out main branch
              uses: actions/checkout@v3
              with:
                  ref: main

            - name: Create Pull Request from main to develop
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  title: "Sync main into develop"
                  body: "Automatically created PR to keep develop up to date with changes from main."
                  base: develop
                  branch: auto/sync-main-to-develop
                  commit-message: "chore: merge main into develop"
                  delete-branch: true
